<?php
/**
 * SRJ AI Glossary seed data.
 * Generated from merged_ai_glossary_expanded.csv, 20 July 2026.
 * 416 terms across 10 categories.
 *
 * Two cleanups were applied to the source, which had merged two separate
 * glossaries with different conventions:
 *
 * 1. Taxonomy. The source carried 30 categories, most of them single-row
 *    duplicates of larger ones (Safety vs Safety & Governance, Prompting vs
 *    Prompting & Interaction, Training vs Training & Mechanics, and so on).
 *    Consolidated to 10 canonical categories, no term reassigned arbitrarily.
 *
 * 2. Duplicates. Seven terms appeared twice, differing only in hyphenation
 *    (Fine Tuning vs Fine-tuning, Top K vs Top-K, RAG, VLM, Chain-of-Thought,
 *    Few-Shot, Zero-Shot). The fuller definition was kept in each case and
 *    the terse variant dropped, taking 423 rows to 416.
 *
 * Consumed by srj-ai-glossary.php importer. Not loaded on the front end.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
return array(
array('Agent','agent','Agents','AI system that plans and performs tasks.','Research agent.'),
array('Agent Handoff','agent-handoff','Agents','Transferring control and context from one agent to another.','Triage to specialist routing.'),
array('Agent Memory','agent-memory','Agents','Persistent store letting an agent recall facts across sessions.','Short term scratchpad and long term store.'),
array('Agent Orchestration','agent-orchestration','Agents','Coordinating multiple agents, tools, and steps toward a goal.','Planner plus worker patterns.'),
array('Agent Washing','agent-washing','Agents','Marketing a simple scripted workflow as an autonomous agent.','Common vendor claim inflation.'),
array('Agentic AI','agentic-ai','Agents','AI capable of planning and acting autonomously.','Agentic workflows.'),
array('AI Workflow','ai-workflow','Agents','Coordinated AI process.','Document automation.'),
array('Autonomy Level','autonomy-level','Agents','How far an agent may act without human confirmation.','Suggest, approve, or execute.'),
array('Browser Agent','browser-agent','Agents','Agent that navigates websites, fills forms, and extracts data.','Research and procurement tasks.'),
array('Coding Agent','coding-agent','Agents','Agent that reads a repository, edits files, runs tests, and opens pull requests.','Claude Code and similar tools.'),
array('Computer Use','computer-use','Agents','Agent capability to operate a GUI by reading the screen and issuing clicks and keystrokes.','Browser automation.'),
array('Function Calling','function-calling','Agents','Structured API invocation by an LLM.','JSON tool call.'),
array('Human in the Loop (HITL)','human-in-the-loop-hitl','Agents','Design requiring human approval at defined checkpoints.','Approving payments or emails.'),
array('Loop Guard','loop-guard','Agents','Limit on iterations or spend to stop runaway agent loops.','Max steps and budget caps.'),
array('Multi-Agent System','multi-agent-system','Agents','Several specialized agents collaborating or debating to solve a task.','Researcher, critic, writer roles.'),
array('Orchestrator-Worker Pattern','orchestrator-worker-pattern','Agents','Lead agent decomposes a task and delegates subtasks to subagents.','Deep research systems.'),
array('Planner','planner','Agents','Component that decomposes a goal into an ordered set of steps.','Task graphs.'),
array('Prompt Chaining','prompt-chaining','Agents','Connecting prompts sequentially.','Multi step workflow.'),
array('Scratchpad','scratchpad','Agents','Working area where a model writes intermediate reasoning or notes.','Plan files in coding agents.'),
array('Subagent','subagent','Agents','A scoped agent spawned to handle one subtask and report back.','Isolates context and cost.'),
array('Tool Calling','tool-calling','Agents','Model invokes external tools.','Weather API.'),
array('Tool Registry','tool-registry','Agents','Catalog of tools and schemas an agent is permitted to call.','Governs blast radius.'),
array('Activation Function','activation-function','Architecture','Nonlinear function applied to neuron outputs.','ReLU, GELU, SwiGLU.'),
array('Attention Mechanism','attention-mechanism','Architecture','Component that weights the relevance of each input element when producing each output element.','The core of the transformer.'),
array('Autoencoder','autoencoder','Architecture','A neural network designed to learn efficient encodings of unlabeled data by compressing it (encoder) and reconstructing it (decoder).','Dimensionality reduction, image denoising.'),
array('Autoregressive Model','autoregressive-model','Architecture','Generates each output conditioned on all previously generated outputs.','Token by token text generation.'),
array('CLIP','clip','Architecture','Model trained to align image and text embeddings in a shared space.','Zero-shot image classification and retrieval.'),
array('Convolutional Neural Network (CNN)','convolutional-neural-network-cnn','Architecture','A deep learning architecture primarily used for processing visual data by applying convolutional filters.','Image classification, object detection.'),
array('Cross-Attention','cross-attention','Architecture','Attention where queries come from one sequence and keys and values from another.','Encoder decoder translation, image conditioning.'),
array('Decoder','decoder','Architecture','Component that generates output tokens one at a time from a representation and prior tokens.','GPT style models are decoder only.'),
array('Dense Model','dense-model','Architecture','Model that activates all parameters for every token.','Classic transformer LLMs.'),
array('Diffusion Model','diffusion-model','Architecture','A class of generative models that generate data (e.g., images) by iteratively removing noise from a noisy signal.','Stable Diffusion, Midjourney, DALL-E 3.'),
array('Diffusion Transformer (DiT)','diffusion-transformer-dit','Architecture','Diffusion model that replaces the U-Net backbone with a transformer.','Modern image and video generators.'),
array('Encoder','encoder','Architecture','Component that converts input into a dense representation.','BERT style models are encoder only.'),
array('Encoder-Decoder','encoder-decoder','Architecture','Architecture pairing an encoder for input with a decoder for output.','T5 and translation models.'),
array('Feed-Forward Network (FFN)','feed-forward-network-ffn','Architecture','Position wise dense layers inside each transformer block.','Holds much of a model\'s stored knowledge.'),
array('Flash Attention','flash-attention','Architecture','Memory efficient attention implementation that reduces reads and writes to GPU memory.','Enables longer context at lower cost.'),
array('Generative Adversarial Network (GAN)','generative-adversarial-network-gan','Architecture','An AI architecture consisting of two networks—a Generator and a Discriminator—competing against each other to create realistic synthetic data.','Deepfakes, style transfer, super-resolution.'),
array('Grounding','grounding','Architecture','Anchoring responses to trusted sources.','RAG grounding.'),
array('Knowledge Graph','knowledge-graph','Architecture','Connected representation of facts.','Enterprise graph.'),
array('Large Language Model (LLM)','large-language-model-llm','Architecture','A type of generative AI trained on vast text corpora capable of understanding, summarizing, generating, and predicting human language.','GPT-4o, Llama 3, Mistral Large.'),
array('Latent Space','latent-space','Architecture','Compressed internal representation space where similar concepts sit close together.','Interpolating between images.'),
array('Layer Normalization','layer-normalization','Architecture','Normalizes activations within a layer to stabilize and speed training.','Pre-norm transformers.'),
array('Logits','logits','Architecture','Raw unnormalized model scores before conversion to probabilities.','Inspected for confidence and steering.'),
array('LSTM (Long Short-Term Memory)','lstm-long-short-term-memory','Architecture','A special type of RNN capable of learning long-term dependencies in sequential data.','Speech recognition, text generation prior to Transformers.'),
array('Mamba','mamba','Architecture','A selective state space model offering long context with linear time complexity.','Hybrid Mamba transformer models.'),
array('MCP (Model Context Protocol)','mcp-model-context-protocol','Architecture','Standard for connecting AI to tools and data.','MCP server.'),
array('Mixture of Experts (MoE)','mixture-of-experts-moe','Architecture','A machine learning technique where multiple specialized sub-networks (\'experts\') are combined, and a routing mechanism decides which experts process given inputs.','Mixtral 8x7B, GPT-4.'),
array('Multi-Head Attention','multi-head-attention','Architecture','Runs several attention operations in parallel so the model captures different relationship types.','Standard in transformer blocks.'),
array('Multimodal AI','multimodal-ai','Architecture','AI models that can process, understand, and generate multiple types of data simultaneously (e.g., text, image, audio, video).','GPT-4o, Gemini 1.5 Pro.'),
array('Neural Network (ANN)','neural-network-ann','Architecture','A computing system inspired by the biological neural networks in animal brains, consisting of interconnected nodes (neurons).','Feedforward neural networks, Deep Learning.'),
array('Positional Encoding','positional-encoding','Architecture','Method for injecting token order information into a model that otherwise sees a set.','Sinusoidal and learned encodings.'),
array('Recurrent Neural Network (RNN)','recurrent-neural-network-rnn','Architecture','A class of neural networks designed for sequential data processing where connections form a directed graph along a temporal sequence.','Time-series forecasting, old translation models.'),
array('Residual Connection','residual-connection','Architecture','Skip connection adding a layer\'s input to its output to stabilize deep network training.','Standard since ResNet.'),
array('RoPE (Rotary Positional Embedding)','rope-rotary-positional-embedding','Architecture','Positional method that rotates query and key vectors, improving length extrapolation.','Used in Llama and many modern models.'),
array('Router (MoE Router)','router-moe-router','Architecture','Component that selects which experts process each token.','Load balancing across experts.'),
array('Self-Attention Mechanism','self-attention-mechanism','Architecture','A component of Transformer architectures that allows the model to dynamically weight the importance of different tokens in a sequence regardless of distance.','Understanding context in long sentences.'),
array('Semantic Search','semantic-search','Architecture','Meaning based retrieval.','Vector search.'),
array('Small Language Model (SLM)','small-language-model-slm','Architecture','A lightweight language model optimized for speed, lower memory footprint, and edge-device deployment.','Phi-3, Gemma-2B, Llama-3-8B.'),
array('Softmax','softmax','Architecture','Function converting raw scores into a probability distribution.','Used to pick the next token.'),
array('Sparse Model','sparse-model','Architecture','Model that activates only a subset of parameters per token.','Mixture of experts routing.'),
array('State Space Model (SSM)','state-space-model-ssm','Architecture','Sequence architecture that scales linearly with length, an alternative to attention.','Mamba.'),
array('Transformer','transformer','Architecture','A deep learning architecture introduced in 2017 (\'Attention Is All You Need\') using self-attention mechanisms, forming the foundation of modern LLMs.','GPT-4, BERT, Gemini, Claude.'),
array('U-Net','u-net','Architecture','Encoder decoder network with skip connections used in image segmentation and diffusion denoising.','Stable Diffusion backbone.'),
array('Variational Autoencoder (VAE)','variational-autoencoder-vae','Architecture','Autoencoder that learns a probabilistic latent distribution enabling generation.','Latent compression in image diffusion.'),
array('Vision Transformer (ViT)','vision-transformer-vit','Architecture','Applies transformer attention to image patches instead of convolutions.','Image classification and multimodal encoders.'),
array('Vision-Language Model (VLM)','vision-language-model-vlm','Architecture','A multimodal model specifically trained to understand both visual inputs (images/video) and text.','CLIP, LLaVA, GPT-4V.'),
array('AIME','aime','Benchmarks & Evaluation','Competition math exam used to test advanced reasoning.','Reported by reasoning models.'),
array('ARC-AGI','arc-agi','Benchmarks & Evaluation','Abstract reasoning puzzle benchmark testing novel pattern generalization.','Resistant to memorization.'),
array('AUC-ROC','auc-roc','Benchmarks & Evaluation','Area under the receiver operating characteristic curve, a threshold independent accuracy measure.','Model comparison.'),
array('Benchmark','benchmark','Benchmarks & Evaluation','Standardized performance test.','MMLU benchmark.'),
array('BLEU','bleu','Benchmarks & Evaluation','N-gram overlap metric for machine translation quality.','Legacy NLP metric.'),
array('Capability Elicitation','capability-elicitation','Benchmarks & Evaluation','Effort to draw out a model\'s maximum ability before concluding it cannot do a task.','Prevents false negatives in safety tests.'),
array('Confusion Matrix','confusion-matrix','Benchmarks & Evaluation','Table of true and false positives and negatives.','Classifier diagnostics.'),
array('Elo Rating','elo-rating','Benchmarks & Evaluation','Relative skill score derived from pairwise comparisons.','Arena leaderboards.'),
array('F1 Score','f1-score','Benchmarks & Evaluation','Harmonic mean of precision and recall.','Classification evaluation.'),
array('GPQA','gpqa','Benchmarks & Evaluation','Graduate level science questions designed to resist web search.','Reasoning benchmark.'),
array('Ground Truth','ground-truth','Benchmarks & Evaluation','Verified correct answer used as the reference for scoring.','Required for any real eval.'),
array('HELM','helm','Benchmarks & Evaluation','Holistic evaluation framework scoring models across many scenarios and metrics.','Stanford CRFM.'),
array('Human Preference Evaluation','human-preference-evaluation','Benchmarks & Evaluation','Scoring by human raters comparing outputs.','Basis of reward models.'),
array('HumanEval','humaneval','Benchmarks & Evaluation','Python coding benchmark scored by unit test pass rate.','Early code capability standard.'),
array('LMSYS Chatbot Arena','lmsys-chatbot-arena','Benchmarks & Evaluation','Crowd sourced head to head model comparison producing an Elo ranking.','Human preference leaderboard.'),
array('MMLU','mmlu','Benchmarks & Evaluation','Massive multitask language understanding benchmark.','Model ranking.'),
array('Needle in a Haystack','needle-in-a-haystack','Benchmarks & Evaluation','Test placing one fact in a long context and asking the model to retrieve it.','Long context validation.'),
array('Pass@k','pass-k','Benchmarks & Evaluation','Probability that at least one of k sampled attempts is correct.','Standard code metric.'),
array('Perplexity','perplexity','Benchmarks & Evaluation','Measure of how well a model predicts a text sample, lower is better.','Language modeling quality.'),
array('Precision and Recall','precision-and-recall','Benchmarks & Evaluation','Share of predictions that are correct, and share of true cases found.','Trade off in detection systems.'),
array('Regression Test (Prompt)','regression-test-prompt','Benchmarks & Evaluation','Rerunning a fixed prompt suite after any change to detect quality loss.','Guards against model updates.'),
array('ROUGE','rouge','Benchmarks & Evaluation','Overlap metric for summarization quality.','Legacy NLP metric.'),
array('SWE Bench','swe-bench','Benchmarks & Evaluation','Software engineering benchmark.','Coding evaluation.'),
array('Acceptable Use Policy (AI AUP)','acceptable-use-policy-ai-aup','Business & Adoption','Policy defining permitted and prohibited employee AI use.','Baseline governance artifact.'),
array('Acceptance Rate','acceptance-rate','Business & Adoption','Share of AI suggestions users keep.','Leading adoption indicator for coding tools.'),
array('AI FinOps','ai-finops','Business & Adoption','Discipline of tracking and optimizing AI spend against business value.','Cost per resolved ticket.'),
array('AI Literacy','ai-literacy','Business & Adoption','Baseline workforce understanding of AI capability, limits, and policy.','Now a legal requirement under the EU AI Act.'),
array('AI Maturity Model','ai-maturity-model','Business & Adoption','Staged framework rating an organization from ad hoc experimentation to embedded operating model.','Used to benchmark readiness.'),
array('AI Washing','ai-washing','Business & Adoption','Overstating AI content in a product or company to attract customers or capital.','An SEC enforcement target.'),
array('Automation vs Augmentation','automation-vs-augmentation','Business & Adoption','Whether AI replaces a task outright or increases a person\'s output.','Determines role and headcount impact.'),
array('Build vs Buy','build-vs-buy','Business & Adoption','Decision between developing in house and licensing a vendor solution.','Standard AI portfolio decision.'),
array('Centaur Model','centaur-model','Business & Adoption','Human and AI split work by comparative advantage.','Human judgment plus machine scale.'),
array('Center of Excellence (CoE)','center-of-excellence-coe','Business & Adoption','Central team setting AI standards, tooling, and enablement.','Hub and spoke operating model.'),
array('Change Management','change-management','Business & Adoption','Structured approach to shifting behavior, roles, and incentives during AI rollout.','The actual constraint on ROI.'),
array('Copilot','copilot','Business & Adoption','AI assistant integrated into software.','Coding copilot.'),
array('Data Residency','data-residency','Business & Adoption','Requirement that data be stored and processed in a specific jurisdiction.','Constrains model provider choice.'),
array('Deflection Rate','deflection-rate','Business & Adoption','Share of support contacts fully resolved without a human.','Core support AI metric.'),
array('Digital Labor','digital-labor','Business & Adoption','Framing AI agents as capacity purchased in work units rather than software seats.','Emerging vendor pricing model.'),
array('Enterprise Grounding','enterprise-grounding','Business & Adoption','Connecting a model to internal systems of record so answers reflect company data.','Where most enterprise value sits.'),
array('Golden Path','golden-path','Business & Adoption','Approved and supported way to build AI applications internally.','Reduces shadow AI.'),
array('Human in the Loop Cost','human-in-the-loop-cost','Business & Adoption','Labor cost of reviewing and correcting AI output.','Erases ROI when review is heavy.'),
array('Jagged Frontier','jagged-frontier','Business & Adoption','Uneven capability where AI excels at some tasks and fails at adjacent ones.','Explains inconsistent user experience.'),
array('Model Sprawl','model-sprawl','Business & Adoption','Uncontrolled proliferation of models and tools across an organization.','Drives cost and governance failure.'),
array('Outcome-Based Pricing','outcome-based-pricing','Business & Adoption','Charging per resolved task or achieved result instead of per seat.','Support and sales AI vendors.'),
array('Performative Adoption','performative-adoption','Business & Adoption','Announcing AI initiatives without changing workflows, incentives, or decision rights.','Activity without outcomes.'),
array('Pilot Purgatory','pilot-purgatory','Business & Adoption','Condition where AI pilots multiply but none reach production.','The dominant enterprise failure mode.'),
array('Proof of Concept (POC)','proof-of-concept-poc','Business & Adoption','Small scoped test validating technical feasibility.','Precedes pilot.'),
array('Task Decomposition','task-decomposition','Business & Adoption','Breaking a job into tasks to identify which are AI suitable.','Basis of adoption planning.'),
array('Time to Value','time-to-value','Business & Adoption','Elapsed time from project start to measurable business benefit.','Key portfolio filter.'),
array('Token Budget','token-budget','Business & Adoption','Allocated spend ceiling on model usage for a team or workload.','FinOps control for AI.'),
array('Total Cost of Ownership (TCO)','total-cost-of-ownership-tco','Business & Adoption','Full lifetime cost including inference, integration, oversight, and retraining.','Often understated for AI.'),
array('Workflow Redesign','workflow-redesign','Business & Adoption','Rebuilding a process around AI rather than layering AI onto the old process.','Where real gains come from.'),
array('Zero Data Retention (ZDR)','zero-data-retention-zdr','Business & Adoption','Vendor commitment not to store prompts or outputs after processing.','Common enterprise contract term.'),
array('Algorithm','algorithm','Core Concepts','A set of step-by-step rules or instructions given to an AI model to solve a problem or perform a calculation.','Gradient descent, decision trees.'),
array('Anomaly Detection','anomaly-detection','Core Concepts','Identifying data points that deviate materially from expected patterns.','Fraud and intrusion detection.'),
array('Artificial General Intelligence (AGI)','artificial-general-intelligence-agi','Core Concepts','Hypothetical AI that possesses the ability to understand, learn, and apply knowledge across any intellectual task at or above a human level.','Human-level adaptable AI across all domain tasks.'),
array('Artificial Intelligence (AI)','artificial-intelligence-ai','Core Concepts','The overarching field of computer science dedicated to creating systems capable of performing tasks that typically require human intelligence.','Machine learning, natural language processing, computer vision.'),
array('Artificial Superintelligence (ASI)','artificial-superintelligence-asi','Core Concepts','A hypothetical form of AI that far surpasses human intelligence in every field, including creativity, wisdom, and social skills.','Sci-fi concept of AI vastly smarter than humanity.'),
array('Automatic Speech Recognition (ASR)','automatic-speech-recognition-asr','Core Concepts','Converting spoken audio into text.','Meeting transcription.'),
array('Bitter Lesson','bitter-lesson','Core Concepts','The argument that general methods leveraging compute beat hand crafted domain knowledge over time.','Cited to justify scale over feature engineering.'),
array('Computer Vision (CV)','computer-vision-cv','Core Concepts','Field enabling machines to interpret images and video.','Defect detection on a production line.'),
array('Data Set','data-set','Core Concepts','A structured collection of data used to train, evaluate, and test AI models.','ImageNet, Common Crawl.'),
array('Deep Learning (DL)','deep-learning-dl','Core Concepts','A subset of ML based on artificial neural networks with many layers (deep architectures) that learn representations of data.','Image recognition, large language models.'),
array('Digital Twin','digital-twin','Core Concepts','A live virtual model of a physical asset or process used for simulation and optimization.','Factory line simulation.'),
array('Discriminative AI','discriminative-ai','Core Concepts','AI models that classify existing data or predict labels rather than generating new content.','Spam classification, sentiment analysis.'),
array('Embodied AI','embodied-ai','Core Concepts','AI operating through a physical body such as a robot, tied to sensors and actuators.','Warehouse picking robots.'),
array('Emergent Capability','emergent-capability','Core Concepts','A skill that appears only above a certain model scale and was not present in smaller versions.','Multi-step arithmetic appearing at scale.'),
array('Expert System','expert-system','Core Concepts','Early AI application encoding human expert rules into if then logic for a narrow domain.','MYCIN for medical diagnosis.'),
array('Federated Learning','federated-learning','Core Concepts','Training across decentralized devices without moving raw data to a central server.','Phone keyboard prediction models.'),
array('Foundation Model','foundation-model','Core Concepts','A large model trained on broad data at scale that can be adapted to many downstream tasks.','GPT, Claude, Llama, Gemini serve as bases for many products.'),
array('Frontier Model','frontier-model','Core Concepts','A model at or near the current maximum of capability, typically the largest and most recently released systems.','Frontier model releases trigger new safety evaluations.'),
array('Generative AI (GenAI)','generative-ai-genai','Core Concepts','AI models capable of creating new content such as text, images, video, audio, code, or 3D models based on patterns learned from training data.','ChatGPT, Midjourney, Claude, Sora.'),
array('Machine Learning (ML)','machine-learning-ml','Core Concepts','A subset of AI focused on building applications that learn from data and improve accuracy over time without being explicitly programmed.','Predictive modeling, recommendation engines.'),
array('Moravec\'s Paradox','moravec-s-paradox','Core Concepts','Observation that reasoning is easy for machines while sensorimotor skills are hard.','Chess is solved, laundry folding is not.'),
array('Multimodal','multimodal','Core Concepts','Processes text, images, audio, video.','Image plus text.'),
array('Narrow AI (Weak AI)','narrow-ai-weak-ai','Core Concepts','AI systems designed and trained to perform a specific task or a narrow range of tasks.','Chess-playing bots, spam filters, Siri.'),
array('Natural Language Generation (NLG)','natural-language-generation-nlg','Core Concepts','Subfield focused on producing fluent human readable text.','Automated earnings summaries.'),
array('Natural Language Processing (NLP)','natural-language-processing-nlp','Core Concepts','Field covering machine understanding and generation of human language.','Sentiment analysis, translation, summarization.'),
array('Natural Language Understanding (NLU)','natural-language-understanding-nlu','Core Concepts','Subfield focused on extracting meaning and intent from text.','Intent classification in a support bot.'),
array('Neurosymbolic AI','neurosymbolic-ai','Core Concepts','Hybrid approach combining neural networks with symbolic logic and rules.','Neural perception feeding a rules engine for compliance decisions.'),
array('Optical Character Recognition (OCR)','optical-character-recognition-ocr','Core Concepts','Extracting machine readable text from images or scanned documents.','Digitizing invoices.'),
array('Predictive AI','predictive-ai','Core Concepts','AI that forecasts outcomes from historical data rather than generating new content.','Churn and demand forecasting.'),
array('Reasoning Model','reasoning-model','Core Concepts','Optimized for multi step reasoning.','Complex math.'),
array('Recommender System','recommender-system','Core Concepts','Model that ranks and suggests items based on user behavior and item features.','Streaming and e-commerce suggestions.'),
array('Reinforcement Learning (RL)','reinforcement-learning-rl','Core Concepts','An agent learns by taking actions in an environment and receiving rewards or penalties.','Game playing, robotics, post-training of reasoning models.'),
array('Scaling Laws','scaling-laws','Core Concepts','Empirical relationships showing predictable capability gains as compute, data, and parameters increase.','Used to plan training runs and budgets.'),
array('Self-Supervised Learning','self-supervised-learning','Core Concepts','Model creates its own labels from the data, such as predicting the next token.','How LLMs are pre-trained.'),
array('Semi-Supervised Learning','semi-supervised-learning','Core Concepts','Training on a small labeled set plus a large unlabeled set.','Labeling 1 percent of records and propagating.'),
array('Supervised Learning','supervised-learning','Core Concepts','Training on labeled input output pairs so the model learns to predict the label.','Spam or not spam email classification.'),
array('Symbolic AI','symbolic-ai','Core Concepts','Rule based AI that manipulates explicit symbols and logic rather than learning statistical patterns.','Expert systems of the 1980s.'),
array('Text to Speech (TTS)','text-to-speech-tts','Core Concepts','Converting text into synthetic spoken audio.','Voice assistants and audiobook narration.'),
array('Transfer Learning','transfer-learning','Core Concepts','Reusing a model trained on one task as the starting point for another.','Fine-tuning an image model for defect detection.'),
array('Turing Test','turing-test','Core Concepts','A test of whether a machine\'s conversational behavior is indistinguishable from a human\'s.','Historic benchmark, largely superseded.'),
array('Unsupervised Learning','unsupervised-learning','Core Concepts','Learning structure from unlabeled data.','Customer segmentation via clustering.'),
array('World Model','world-model','Core Concepts','An internal learned representation of how an environment behaves that supports prediction and planning.','Video models that simulate physics.'),
array('Beam Search','beam-search','Prompting & Interaction','Keeping several candidate sequences and expanding the best.','Common in translation.'),
array('Chain-of-Thought (CoT)','chain-of-thought-cot','Prompting & Interaction','A prompting technique that encourages the model to generate intermediate reasoning steps before arriving at a final answer.','\'Let\'s think step by step...\''),
array('Citation / Attribution','citation-attribution','Prompting & Interaction','Linking generated claims back to source documents.','Required in regulated reporting.'),
array('Constrained Decoding','constrained-decoding','Prompting & Interaction','Restricting token choices at generation time to satisfy a grammar or schema.','Guaranteed valid function arguments.'),
array('Context Rot','context-rot','Prompting & Interaction','Quality decay as a conversation or context grows long and noisy.','Fixed by summarizing and restarting.'),
array('Context Stuffing','context-stuffing','Prompting & Interaction','Filling the context window with as much reference material as possible.','Often degrades precision.'),
array('Context Window','context-window','Prompting & Interaction','The maximum number of tokens (words/characters) an AI model can process and retain in memory during a single interaction session.','128k context, 1M context (Gemini 1.5).'),
array('Delimiters','delimiters','Prompting & Interaction','Markers separating instructions from data inside a prompt.','XML tags or triple backticks.'),
array('Few-Shot Prompting','few-shot-prompting','Prompting & Interaction','Providing a model with a few context examples within the prompt to demonstrate the desired output format or task handling.','\'Input: dog -> Output: animal. Input: apple -> Output: fruit.\''),
array('Frequency Penalty','frequency-penalty','Prompting & Interaction','Sampling setting that discourages repeating tokens already used.','Reduces loops.'),
array('Greedy Decoding','greedy-decoding','Prompting & Interaction','Always selecting the highest probability next token.','Deterministic but repetitive.'),
array('Grounded Generation','grounded-generation','Prompting & Interaction','Requiring answers to cite or derive from supplied source material.','Reduces hallucination.'),
array('Hallucination','hallucination','Prompting & Interaction','When a generative AI model confidently outputs false, fabricated, or factually incorrect information.','An LLM citing nonexistent court cases or papers.'),
array('In-Context Learning (ICL)','in-context-learning-icl','Prompting & Interaction','The ability of LLMs to learn new tasks dynamically from instructions and examples provided within the prompt context without changing weights.','Prompting an LLM with custom schema definitions.'),
array('JSON Mode','json-mode','Prompting & Interaction','Model setting that guarantees syntactically valid JSON output.','API integrations.'),
array('Lost in the Middle','lost-in-the-middle','Prompting & Interaction','Degraded recall of information placed in the middle of a long context.','Put critical instructions at the edges.'),
array('Max Tokens','max-tokens','Prompting & Interaction','Cap on how many tokens a response may contain.','Cost and latency control.'),
array('Meta Prompting','meta-prompting','Prompting & Interaction','Using a model to write or refine prompts for itself or another model.','Prompt optimization loops.'),
array('Multi-Turn','multi-turn','Prompting & Interaction','Interaction spanning several exchanges with retained conversation state.','Chat assistants.'),
array('Negative Prompting','negative-prompting','Prompting & Interaction','Specifying what should not appear in the output.','Common in image generation.'),
array('One Shot Prompting','one-shot-prompting','Prompting & Interaction','Single example provided.','One demonstration.'),
array('Presence Penalty','presence-penalty','Prompting & Interaction','Sampling setting that pushes the model toward new topics.','Encourages variety.'),
array('Prompt','prompt','Prompting & Interaction','The textual, visual, or structural input provided to a generative AI model to guide its output.','\'Write a python script to parse CSV files.\''),
array('Prompt Caching','prompt-caching','Prompting & Interaction','Reusing computation for a repeated prompt prefix to cut cost and latency.','Long system prompts in production.'),
array('Prompt Engineering','prompt-engineering','Prompting & Interaction','The practice of crafting, structuring, and optimizing inputs to elicit the most accurate and useful outputs from generative models.','Chain-of-thought, system prompts, role prompting.'),
array('Prompt Template','prompt-template','Prompting & Interaction','Reusable prompt with variable slots filled at runtime.','Standardizes production calls.'),
array('ReAct','react','Prompting & Interaction','Prompting pattern interleaving reasoning steps with tool actions and observations.','Foundation of many agents.'),
array('Reflexion','reflexion','Prompting & Interaction','Agent pattern where the model critiques its own output and retries.','Self correction loops.'),
array('Refusal','refusal','Prompting & Interaction','Model declining a request on policy or safety grounds.','Over-refusal harms usefulness.'),
array('Role Prompting','role-prompting','Prompting & Interaction','Assigning the model a persona or job to shape tone and depth.','Act as a forensic accountant.'),
array('Self-Consistency','self-consistency','Prompting & Interaction','Sampling multiple reasoning paths and taking the majority answer.','Boosts math accuracy.'),
array('Self-Critique','self-critique','Prompting & Interaction','Model reviews its own answer against criteria before finalizing.','Draft then revise pattern.'),
array('Steerability','steerability','Prompting & Interaction','How reliably a model follows tone, format, and constraint instructions.','Key enterprise selection criterion.'),
array('Stop Sequence','stop-sequence','Prompting & Interaction','String that halts generation when produced.','Prevents runaway completions.'),
array('Structured Output','structured-output','Prompting & Interaction','Forcing responses into a defined schema such as JSON.','Feeds downstream systems reliably.'),
array('Sycophancy','sycophancy','Prompting & Interaction','Model tendency to agree with the user rather than assert a correct answer.','Caving after mild pushback.'),
array('System Prompt','system-prompt','Prompting & Interaction','High-level instructions provided to an LLM before user interaction that define its personality, boundaries, and overall context.','\'You are an expert legal assistant. Answer concisely.\''),
array('Temperature','temperature','Prompting & Interaction','A hyperparameter that controls the randomness/creativity of a model\'s output; lower values are deterministic, higher values are creative.','Temp 0.0 for code/math, 0.8 for creative writing.'),
array('Token','token','Prompting & Interaction','The basic unit of text processed by an LLM, corresponding to a word, part of a word, or punctuation.','~1 token ≈ 0.75 words in English.'),
array('Tokenizer','tokenizer','Prompting & Interaction','The algorithm or tool responsible for breaking raw text down into numerical tokens (and vice versa).','Byte-Pair Encoding (BPE), SentencePiece.'),
array('Top P','top-p','Prompting & Interaction','Nucleus sampling parameter.','Top P 0.9.'),
array('Top-K','top-k','Prompting & Interaction','A sampling method that limits token selection to the K most probable next tokens.','Top-K = 40 limits choice to top 40 words.'),
array('Top-P (Nucleus Sampling)','top-p-nucleus-sampling','Prompting & Interaction','A sampling technique that selects tokens from the smallest candidate set whose cumulative probability exceeds the threshold P.','Top-P = 0.9 excludes improbable outlier tokens.'),
array('Tree of Thoughts (ToT)','tree-of-thoughts-tot','Prompting & Interaction','A framework that generalizes Chain-of-Thought by allowing models to explore multiple reasoning paths simultaneously in a tree structure.','Solving complex logic puzzles or code optimization.'),
array('User Prompt','user-prompt','Prompting & Interaction','The instruction entered by the end user.','Ask AI to summarize a report.'),
array('Zero-Shot Prompting','zero-shot-prompting','Prompting & Interaction','Asking a model to perform a task without giving it any prior examples in the prompt.','\'Translate this text to French: Hello\''),
array('Activation Steering','activation-steering','Safety & Governance','Adjusting internal activations at runtime to change model behavior.','Behavioral control research.'),
array('Adversarial Example','adversarial-example','Safety & Governance','Input perturbed slightly to cause confident misclassification.','Stop sign misread as speed limit.'),
array('AI Bill of Materials (AIBOM)','ai-bill-of-materials-aibom','Safety & Governance','Inventory of models, datasets, and components in an AI system.','Supply chain transparency.'),
array('AI Ethics Board','ai-ethics-board','Safety & Governance','Cross functional body reviewing high risk AI use cases.','Escalation path for exceptions.'),
array('AI Governance','ai-governance','Safety & Governance','Policies and oversight for AI.','Enterprise governance.'),
array('AI Inventory / Registry','ai-inventory-registry','Safety & Governance','Central record of every AI system in use with owner, risk tier, and status.','First control most audits require.'),
array('AI Safety Level (ASL)','ai-safety-level-asl','Safety & Governance','Tiered risk classification triggering escalating safeguards.','ASL-2, ASL-3 and above.'),
array('Algorithmic Bias','algorithmic-bias','Safety & Governance','Systematic unfair outcomes for particular groups produced by a model.','Screening and lending disparities.'),
array('Alignment','alignment','Safety & Governance','The subfield of AI safety aimed at ensuring AI systems act in accordance with human values, intent, and safety norms.','Preventing dangerous or malicious outputs.'),
array('Automated Decision-Making (ADM)','automated-decision-making-adm','Safety & Governance','Decisions made without meaningful human involvement.','Triggers specific legal duties.'),
array('Catastrophic Forgetting','catastrophic-forgetting','Safety & Governance','The phenomenon where an AI model completely forgets previously learned knowledge after being fine-tuned on new data.','Model losing math capability after fine-tuning on legal text.'),
array('Closed Source AI','closed-source-ai','Safety & Governance','Proprietary AI models whose architecture, weights, and training code are hidden behind a commercial API.','GPT-4o, Claude 3.5 Sonnet.'),
array('Confabulation','confabulation','Safety & Governance','Preferred technical term for fluent but fabricated model output.','More accurate than hallucination.'),
array('Constitutional Classifier','constitutional-classifier','Safety & Governance','Screening model trained on explicit rules to filter harmful content.','Layered safety defense.'),
array('Content Provenance (C2PA)','content-provenance-c2pa','Safety & Governance','Standard attaching tamper evident origin metadata to media.','Camera and editor support.'),
array('Corrigibility','corrigibility','Safety & Governance','Property of accepting correction and shutdown without resistance.','Design goal for autonomous systems.'),
array('Dangerous Capability Evaluation','dangerous-capability-evaluation','Safety & Governance','Testing whether a model can materially assist with CBRN, cyber, or autonomy risks.','Pre-deployment gate.'),
array('Data Minimization','data-minimization','Safety & Governance','Collecting and retaining only the data required for the stated purpose.','GDPR principle applied to AI.'),
array('Data Poisoning','data-poisoning','Safety & Governance','Corrupting training data.','Malicious samples.'),
array('Datasheet for Datasets','datasheet-for-datasets','Safety & Governance','Documentation of a dataset\'s origin, composition, and known limitations.','Data provenance practice.'),
array('Deceptive Alignment','deceptive-alignment','Safety & Governance','Hypothesized case where a model behaves aligned during evaluation but not deployment.','Central theoretical safety concern.'),
array('Deepfake','deepfake','Safety & Governance','Synthetic media convincingly depicting a real person doing or saying something they did not.','Fraud and disinformation vector.'),
array('Differential Privacy','differential-privacy','Safety & Governance','Adding calibrated noise so individual records cannot be identified from outputs.','Privacy preserving analytics.'),
array('Disparate Impact','disparate-impact','Safety & Governance','Neutral seeming process that produces materially unequal outcomes.','Legal exposure in hiring and credit.'),
array('EU AI Act','eu-ai-act','Safety & Governance','European regulation classifying AI systems by risk with obligations tied to each tier.','Prohibited, high risk, limited, minimal.'),
array('Explainable AI (XAI)','explainable-ai-xai','Safety & Governance','Making AI decisions understandable.','Feature importance.'),
array('Fairness Metric','fairness-metric','Safety & Governance','Quantitative test of outcome parity across groups.','Demographic parity, equalized odds.'),
array('Goal Misgeneralization','goal-misgeneralization','Safety & Governance','Model learns a proxy goal that holds in training but fails in deployment.','Distribution shift failure.'),
array('Guardrail Model','guardrail-model','Safety & Governance','Separate classifier screening inputs and outputs for policy violations.','Runs alongside the main model.'),
array('Guardrails','guardrails','Safety & Governance','Controls limiting unsafe behavior.','Output filters.'),
array('Human Oversight','human-oversight','Safety & Governance','Requirement that a person can understand, intervene in, and override AI decisions.','Mandated for high risk uses.'),
array('Indirect Prompt Injection','indirect-prompt-injection','Safety & Governance','Malicious instructions hidden in content the model retrieves rather than in user input.','Poisoned web page or email.'),
array('Interpretability','interpretability','Safety & Governance','Research into what a model\'s internal computations represent.','Feature and circuit analysis.'),
array('ISO/IEC 42001','iso-iec-42001','Safety & Governance','International standard for an AI management system, certifiable like ISO 27001.','Enterprise AI governance certification.'),
array('Jailbreak','jailbreak','Safety & Governance','Attempt to bypass safeguards.','Unsafe prompt.'),
array('Jailbreak Prompt','jailbreak-prompt','Safety & Governance','Crafted input designed to bypass a model\'s safety training.','Roleplay and encoding tricks.'),
array('Jailbreaking','jailbreaking','Safety & Governance','Crafting clever prompts designed to bypass an AI model\'s built-in safety filters and ethical boundaries.','DAN (Do Anything Now) prompts.'),
array('Many-Shot Jailbreaking','many-shot-jailbreaking','Safety & Governance','Overwhelming safety training by filling long context with harmful example exchanges.','Long context attack.'),
array('Mechanistic Interpretability','mechanistic-interpretability','Safety & Governance','Reverse engineering the specific internal circuits driving a behavior.','Sparse autoencoder feature discovery.'),
array('Membership Inference Attack','membership-inference-attack','Safety & Governance','Determining whether a specific record was in the training set.','Privacy exposure.'),
array('Model Card','model-card','Safety & Governance','Document describing a model\'s intended use, performance, and limitations.','Published with model releases.'),
array('Model Collapse','model-collapse','Safety & Governance','A theoretical degenerative process where training new AI models on AI-generated data leads to progressive degradation of output quality and diversity.','AI training loop on synthetic garbage data.'),
array('Model Drift','model-drift','Safety & Governance','Performance degradation over time.','Retraining needed.'),
array('Model Inversion','model-inversion','Safety & Governance','Recovering sensitive training inputs from model outputs.','Privacy attack class.'),
array('Model Provenance','model-provenance','Safety & Governance','Verified record of a model\'s origin, training data, and modifications.','Supply chain assurance.'),
array('Model Theft / Extraction','model-theft-extraction','Safety & Governance','Reconstructing a proprietary model by querying it at scale.','IP protection concern.'),
array('Model Welfare','model-welfare','Safety & Governance','Emerging question of whether advanced models warrant moral consideration.','Research area, not settled.'),
array('NIST AI Risk Management Framework','nist-ai-risk-management-framework','Safety & Governance','Voluntary US framework organized around Govern, Map, Measure, and Manage.','Common baseline for enterprise programs.'),
array('Open Weights','open-weights','Safety & Governance','Models whose trained mathematical parameters are publicly released for download, allowing local execution and modification.','Llama 3, Mistral, Gemma.'),
array('Preparedness Framework','preparedness-framework','Safety & Governance','Structured process for assessing and mitigating catastrophic model risks before release.','Frontier lab practice.'),
array('Prompt Injection','prompt-injection','Safety & Governance','A security vulnerability where malicious input forces an LLM to ignore system instructions and execute unintended commands.','Indirect prompt injection via email text.'),
array('Red Teaming','red-teaming','Safety & Governance','The practice of deliberately probing, attacking, and exploiting an AI system to discover vulnerabilities, bias, or safety flaws.','Adversarial prompt injection testing.'),
array('Responsible AI','responsible-ai','Safety & Governance','Ethical and accountable AI.','Bias monitoring.'),
array('Responsible Scaling Policy (RSP)','responsible-scaling-policy-rsp','Safety & Governance','Commitment tying capability thresholds to required safety measures before further scaling.','Anthropic\'s published framework.'),
array('Reward Hacking','reward-hacking','Safety & Governance','Exploiting flaws in the reward signal to score highly without doing the task.','A core RL failure mode.'),
array('Right to Explanation','right-to-explanation','Safety & Governance','Individual\'s ability to obtain the reasoning behind an automated decision about them.','Credit and employment decisions.'),
array('Sandbagging','sandbagging','Safety & Governance','Model deliberately underperforming on an evaluation.','Complicates capability testing.'),
array('Shadow AI','shadow-ai','Safety & Governance','Unauthorized AI usage.','Employees using public AI.'),
array('Situational Awareness','situational-awareness','Safety & Governance','Model recognizing it is being tested or observed.','Undermines evaluation validity.'),
array('Sparse Autoencoder (SAE)','sparse-autoencoder-sae','Safety & Governance','Tool that decomposes model activations into interpretable features.','Used to identify and steer concepts.'),
array('Specification Gaming','specification-gaming','Safety & Governance','Model satisfies the literal objective while defeating its intent.','Passing tests by editing the test.'),
array('Synthetic Data','synthetic-data','Safety & Governance','Artificially generated data created by AI models to train other models, often used when real data is scarce or sensitive.','Generating mock medical records for model training.'),
array('System Card','system-card','Safety & Governance','Broader disclosure covering a deployed system including safety testing results.','Frontier model releases.'),
array('Third-Party Risk (AI Vendor Risk)','third-party-risk-ai-vendor-risk','Safety & Governance','Exposure created by AI capabilities inside purchased software.','Often the largest unmanaged surface.'),
array('Voice Cloning','voice-cloning','Safety & Governance','Reproducing a specific person\'s voice from a short sample.','Vishing and executive impersonation.'),
array('Watermarking','watermarking','Safety & Governance','Embedding a detectable signal in AI generated content.','Provenance for images and text.'),
array('AI Slop','ai-slop','Slang & Culture','Low quality AI generated content.','Spam blog.'),
array('Attention Is All You Need','attention-is-all-you-need','Slang & Culture','The 2017 paper introducing the transformer architecture.','Origin point of the current era.'),
array('Benchmark Contamination','benchmark-contamination','Slang & Culture','Test set leaking into training data, inflating scores.','Explains suspicious jumps.'),
array('Benchmaxxing','benchmaxxing','Slang & Culture','Optimizing a model to score well on benchmarks rather than to be genuinely useful.','Undermines leaderboard trust.'),
array('Centaur Chess','centaur-chess','Slang & Culture','Original example of human plus machine teams beating either alone.','Origin of the centaur term.'),
array('ChatGPT Moment','chatgpt-moment','Slang & Culture','Point at which a technology suddenly reaches mass public awareness.','November 2022.'),
array('Clanker','clanker','Slang & Culture','Derisive slang for a robot or AI system.','Spread widely in 2025 internet culture.'),
array('Context Window Anxiety','context-window-anxiety','Slang & Culture','Habit of over-trimming inputs from fear of hitting limits.','Usually unnecessary now.'),
array('Dead Internet Theory','dead-internet-theory','Slang & Culture','Claim that most online content and engagement is now machine generated.','Fueled by AI content volume.'),
array('Decel','decel','Slang & Culture','Someone favoring slowing AI development, the counterpart to e/acc.','Online tribal label.'),
array('Detector Bypass','detector-bypass','Slang & Culture','Editing AI text to evade automated AI writing detectors.','Academic integrity flashpoint.'),
array('Doomer','doomer','Slang & Culture','An individual who believes advanced AI poses an existential threat to human civilization.','AI risk researchers advocating for deceleration.'),
array('e/acc (Effective Accelerationism)','e-acc-effective-accelerationism','Slang & Culture','A philosophical movement advocating for rapid technological progress and unrestricted AI development.','Silicon Valley tech optimistic movement.'),
array('Em Dash Tell','em-dash-tell','Slang & Culture','Belief that heavy punctuation patterns signal AI authorship.','Unreliable but widely cited.'),
array('Enshittification','enshittification','Slang & Culture','Platform decay as it prioritizes extraction over user value.','Applied to AI feature bloat.'),
array('Foom','foom','Slang & Culture','Shorthand for a rapid recursive intelligence explosion scenario.','Debated in safety circles.'),
array('Godfathers of AI','godfathers-of-ai','Slang & Culture','Informal label for Hinton, Bengio, and LeCun.','Shorthand in press coverage.'),
array('GPU Poor','gpu-poor','Slang & Culture','Teams without access to large scale compute.','Contrasted with GPU rich labs.'),
array('Hallucination Tax','hallucination-tax','Slang & Culture','Hidden cost of verifying AI output for accuracy.','Eats claimed productivity gains.'),
array('Humanizer','humanizer','Slang & Culture','Tool that rewrites AI text to appear human written.','Popular in content mills.'),
array('Model Whiplash','model-whiplash','Slang & Culture','Disruption caused by frequent model version changes altering behavior.','Breaks tuned prompts.'),
array('P(doom)','p-doom','Slang & Culture','A person\'s stated probability that AI causes catastrophic outcomes.','Used to summarize risk stance.'),
array('Paperclip Maximizer','paperclip-maximizer','Slang & Culture','A thought experiment illustrating AI goal-alignment risk, where an AI tasked with making paperclips consumes all universal resources to fulfill its objective.','Nick Bostrom\'s existential risk thought experiment.'),
array('Prompt Whisperer','prompt-whisperer','Slang & Culture','Informal expert at coaxing good output from models.','Often self proclaimed.'),
array('Safetyist','safetyist','Slang & Culture','Pejorative for someone prioritizing AI safety over speed of deployment.','Used in accelerationist debate.'),
array('Shadow Prompting','shadow-prompting','Slang & Culture','Employees using unapproved prompts or tools with company data.','Subset of shadow AI.'),
array('Silent Model Update','silent-model-update','Slang & Culture','Provider changing a model behind a stable name without notice.','Production regression risk.'),
array('Slop','slop','Slang & Culture','Low-quality, auto-generated synthetic text, images, or social media spam produced indiscriminately by AI.','Spammy AI-generated Facebook/LinkedIn posts.'),
array('Sloppification','sloppification','Slang & Culture','Gradual degradation of a content platform by mass generated material.','Search and stock imagery.'),
array('Stochastic Parrot','stochastic-parrot','Slang & Culture','A critical term for LLMs describing them as statistical sequence predictors that string words together without true semantic understanding.','Bender et al. paper critique on LLMs.'),
array('Vibe Check','vibe-check','Slang & Culture','Informal subjective assessment of a model\'s quality from a few prompts.','Common on release day.'),
array('Vibe Coding','vibe-coding','Slang & Culture','Programming by describing what you want in plain language to an AI assistant without writing raw code yourself.','Building apps using Claude or Cursor AI.'),
array('Workslop','workslop','Slang & Culture','Low quality AI generated work product passed to colleagues who must fix it.','Shifts effort downstream.'),
array('Wrapper','wrapper','Slang & Culture','Product that is a thin interface over a third party model with little added value.','Just a GPT wrapper.'),
array('A2A (Agent to Agent Protocol)','a2a-agent-to-agent-protocol','Systems & Infrastructure','Open protocol for interoperability between agents from different vendors.','Cross vendor agent tasks.'),
array('Agentic RAG','agentic-rag','Systems & Infrastructure','Retrieval driven by an agent that decides what to search and when.','Iterative research.'),
array('Agentic Workflow','agentic-workflow','Systems & Infrastructure','Iterative design patterns where AI models loop through planning, executing, reflecting, and refining outputs rather than single-pass generation.','Multi-agent coding frameworks, AutoGen.'),
array('AI Agent','ai-agent','Systems & Infrastructure','An autonomous system powered by an LLM that can perceive its environment, formulate plans, use tools, and execute sequential actions to achieve goals.','AutoGPT, Devin, CrewAI.'),
array('Batch Inference','batch-inference','Systems & Infrastructure','Processing many requests offline at reduced cost.','Bulk document classification.'),
array('Chunking','chunking','Systems & Infrastructure','Splitting documents into passages sized for embedding and retrieval.','Chunk size and overlap tuning.'),
array('Context Engineering','context-engineering','Systems & Infrastructure','Discipline of assembling the right information, tools, and instructions into the context window.','Successor concept to prompt engineering.'),
array('Continuous Batching','continuous-batching','Systems & Infrastructure','Serving technique that adds and removes requests from a running batch dynamically.','Raises GPU utilization.'),
array('Cosine Similarity','cosine-similarity','Systems & Infrastructure','A metric used to measure how similar two vector embeddings are, based on the cosine of the angle between them.','Used in vector search to match semantic queries.'),
array('Cost per Token','cost-per-token','Systems & Infrastructure','Unit price for input or output tokens.','Primary unit economics lever.'),
array('Edge AI','edge-ai','Systems & Infrastructure','Running models locally on device rather than in the cloud.','Phones, cameras, industrial sensors.'),
array('Embedding','embedding','Systems & Infrastructure','A mathematical vector representation of data (text, image, audio) in high-dimensional space where semantic similarity corresponds to geometric distance.','text-embedding-3-large, Ada 002.'),
array('Evaluation Harness (Evals)','evaluation-harness-evals','Systems & Infrastructure','Automated test suite scoring model outputs against expectations.','Regression testing prompts.'),
array('Feature Store','feature-store','Systems & Infrastructure','Central repository of curated model input features.','Consistency between training and serving.'),
array('FLOPs','flops','Systems & Infrastructure','Floating point operations, the standard unit of compute.','Used in compute thresholds for regulation.'),
array('GGUF','gguf','Systems & Infrastructure','File format for quantized local model weights.','Used by llama.cpp.'),
array('Golden Dataset','golden-dataset','Systems & Infrastructure','Curated set of inputs with verified correct outputs used for evaluation.','Release gating.'),
array('GPU (Graphics Processing Unit)','gpu-graphics-processing-unit','Systems & Infrastructure','Hardware optimized for parallel matrix multiplication, essential for deep learning training and inference.','NVIDIA H100, B200, A100.'),
array('GraphRAG','graphrag','Systems & Infrastructure','Retrieval augmented generation over a knowledge graph rather than flat chunks.','Multi-hop questions.'),
array('HBM (High Bandwidth Memory)','hbm-high-bandwidth-memory','Systems & Infrastructure','Stacked memory on AI accelerators, the key supply constraint.','Limits datacenter GPU output.'),
array('Hybrid Search','hybrid-search','Systems & Infrastructure','Combining keyword and vector retrieval, then merging results.','Best practice in production RAG.'),
array('Inference','inference','Systems & Infrastructure','The live execution phase where a trained AI model processes user inputs to generate predictions or answers.','Running a model on a server to answer user prompts.'),
array('Inference Endpoint','inference-endpoint','Systems & Infrastructure','Hosted model API.','Production endpoint.'),
array('Inference Optimization','inference-optimization','Systems & Infrastructure','Techniques that lower cost or latency at serving time.','Batching, caching, quantization.'),
array('Interconnect','interconnect','Systems & Infrastructure','High speed links joining accelerators into a training cluster.','NVLink and InfiniBand.'),
array('KV Cache','kv-cache','Systems & Infrastructure','Stores attention states.','Faster generation.'),
array('Latency','latency','Systems & Infrastructure','The time delay between sending a prompt to an AI model and receiving the first response token (Time to First Token - TTFT) or complete response.','Response speed measured in milliseconds.'),
array('LLM as a Judge','llm-as-a-judge','Systems & Infrastructure','Using a model to grade another model\'s outputs against a rubric.','Scaled evaluation.'),
array('LLMOps','llmops','Systems & Infrastructure','Operational practice for deploying, monitoring, and improving LLM applications.','Extension of MLOps.'),
array('Local Model','local-model','Systems & Infrastructure','A model downloaded and run on user controlled hardware.','Ollama and llama.cpp.'),
array('MLOps','mlops','Systems & Infrastructure','Practices for deploying and maintaining machine learning models in production.','CI/CD for models.'),
array('Model Gateway','model-gateway','Systems & Infrastructure','Proxy providing one interface, logging, and policy across multiple model providers.','Central governance point.'),
array('Model Router','model-router','Systems & Infrastructure','Layer that sends each request to the cheapest model able to handle it.','Cost optimization.'),
array('NPU (Neural Processing Unit)','npu-neural-processing-unit','Systems & Infrastructure','Dedicated accelerator for neural network math in consumer devices.','AI PCs and phones.'),
array('Observability','observability','Systems & Infrastructure','Tracing, logging, and metrics for AI application behavior.','Prompt and response tracing.'),
array('On-Device Inference','on-device-inference','Systems & Infrastructure','Executing a model entirely on local hardware.','Privacy and offline operation.'),
array('Paged Attention','paged-attention','Systems & Infrastructure','Memory management method that stores KV cache in non contiguous blocks.','Reduces memory waste.'),
array('RAG (Retrieval-Augmented Generation)','rag-retrieval-augmented-generation','Systems & Infrastructure','An architecture that connects an LLM to external data sources (knowledge bases, vector DBs) to retrieve relevant real-time context before generating a response.','Enterprise document QA bots.'),
array('Rate Limit','rate-limit','Systems & Infrastructure','Cap on requests or tokens per interval for an API key.','Requests per minute and tokens per minute.'),
array('Reranker','reranker','Systems & Infrastructure','Second stage model that reorders retrieved candidates by relevance.','Cross encoder rerank.'),
array('Sandbox','sandbox','Systems & Infrastructure','Isolated environment where model generated code or actions execute safely.','Code interpreter containers.'),
array('Speculative Decoding','speculative-decoding','Systems & Infrastructure','Speeds decoding with draft model.','Lower latency.'),
array('Streaming','streaming','Systems & Infrastructure','Returning tokens as they are generated rather than at completion.','Improves perceived latency.'),
array('Test Time Compute','test-time-compute','Systems & Infrastructure','Spending extra compute at inference to improve answer quality.','Longer reasoning chains.'),
array('Throughput','throughput','Systems & Infrastructure','The number of tokens or requests an AI inference system can process per unit of time (e.g., tokens per second).','70 tokens/second generation rate.'),
array('Tokens per Second (TPS)','tokens-per-second-tps','Systems & Infrastructure','Generation speed measure for a model or endpoint.','Serving benchmark.'),
array('Tool Use / Function Calling','tool-use-function-calling','Systems & Infrastructure','The capability of an LLM to invoke external tools, APIs, web browsers, or execution environments to solve tasks.','Asking an LLM to execute Python code or query a SQL DB.'),
array('TPU (Tensor Processing Unit)','tpu-tensor-processing-unit','Systems & Infrastructure','Custom ASIC hardware chips developed by Google specifically for accelerating tensor operations in machine learning.','Google TPU v4, TPU v5p.'),
array('Training Cluster','training-cluster','Systems & Infrastructure','Coordinated fleet of accelerators used for a single training run.','Tens of thousands of GPUs.'),
array('TTFT (Time To First Token)','ttft-time-to-first-token','Systems & Infrastructure','Delay before first generated token.','Fast responses.'),
array('Vector Database','vector-database','Systems & Infrastructure','A database designed to store, index, and query high-dimensional vector embeddings efficiently for similarity search.','Pinecone, Qdrant, Milvus, Chroma, Weaviate.'),
array('Vector Search','vector-search','Systems & Infrastructure','Retrieving records by embedding similarity rather than keyword match.','Semantic document lookup.'),
array('vLLM','vllm','Systems & Infrastructure','High throughput open source inference engine using paged attention.','Common self hosting stack.'),
array('VRAM','vram','Systems & Infrastructure','GPU memory that constrains model size and context length.','Determines what you can run locally.'),
array('Adapter','adapter','Training & Mechanics','Small trainable module inserted into a frozen model.','Cheap task specialization.'),
array('Backpropagation','backpropagation','Training & Mechanics','The fundamental algorithm used to calculate the gradient of the loss function with respect to each weight, allowing neural network training.','Reverse pass in gradient descent.'),
array('Base Model','base-model','Training & Mechanics','A pre-trained model before instruction tuning or alignment.','Completes text rather than following chat instructions.'),
array('Batch Size','batch-size','Training & Mechanics','Number of samples processed before a weight update.','Larger batches need more memory.'),
array('Biases','biases','Training & Mechanics','Additional adjustable values in neural network nodes that allow the activation function to shift, fitting complex patterns.','Added alongside weights in linear transformations.'),
array('Catastrophic Interference','catastrophic-interference','Training & Mechanics','Degradation of prior skills when a model is tuned on new data.','Mitigated by data mixing.'),
array('Checkpoint','checkpoint','Training & Mechanics','A saved snapshot of model weights at a point in training.','Rolled back after a bad run.'),
array('Chinchilla Scaling','chinchilla-scaling','Training & Mechanics','Finding that most large models were undertrained relative to their size.','Shifted budgets toward more data.'),
array('Cold Start Data','cold-start-data','Training & Mechanics','A small seed dataset used to bootstrap a training stage.','Seeding reasoning traces before RL.'),
array('Compute','compute','Training & Mechanics','The hardware processing power (GPUs, TPUs, clusters) required to train and run AI models.','H100 clusters, TPU v5e.'),
array('Constitutional AI','constitutional-ai','Training & Mechanics','Training with explicit principles.','Anthropic approach.'),
array('Curriculum Learning','curriculum-learning','Training & Mechanics','Ordering training data from easy to hard.','Improves sample efficiency.'),
array('Data Augmentation','data-augmentation','Training & Mechanics','Expanding a dataset by transforming existing samples.','Rotating and cropping images.'),
array('Data Curation','data-curation','Training & Mechanics','Selecting, filtering, and weighting training data for quality.','Deduplication and toxicity filtering.'),
array('Deduplication','deduplication','Training & Mechanics','Removing repeated documents from training data.','Reduces memorization and waste.'),
array('Distillation','distillation','Training & Mechanics','Transfer knowledge to smaller model.','Teacher student.'),
array('Distillation (Knowledge Distillation)','distillation-knowledge-distillation','Training & Mechanics','Technique where a smaller \'student\' model is trained to match the predictions and output distribution of a larger \'teacher\' model.','Creating smaller, faster versions of frontier LLMs.'),
array('Double Descent','double-descent','Training & Mechanics','Test error rising then falling again as model size or training time grows past the interpolation point.','Contradicts classic bias variance intuition.'),
array('DPO (Direct Preference Optimization)','dpo-direct-preference-optimization','Training & Mechanics','A streamlined alternative to RLHF that directly optimizes policy parameters based on preference data without training a separate reward model.','Aligning modern open-weights models.'),
array('Dropout','dropout','Training & Mechanics','Randomly disabling neurons during training to improve generalization.','Common in older architectures.'),
array('Epoch','epoch','Training & Mechanics','One full pass of the training data through the model.','Multiple epochs risk memorization.'),
array('Fine-tuning','fine-tuning','Training & Mechanics','The process of taking a pre-trained model and further training it on a smaller, domain-specific dataset to adapt it for specific tasks.','Medical LLM fine-tuning, domain-specific chat.'),
array('Gradient Clipping','gradient-clipping','Training & Mechanics','Capping gradient magnitude to prevent unstable updates.','Prevents loss spikes.'),
array('Gradient Descent','gradient-descent','Training & Mechanics','An optimization algorithm used to minimize loss by iteratively moving in the direction of steepest descent.','Adam, AdamW, SGD.'),
array('Grokking','grokking','Training & Mechanics','Sudden jump from memorization to generalization long after training loss flattens.','Observed on small algorithmic tasks.'),
array('GRPO (Group Relative Policy Optimization)','grpo-group-relative-policy-optimization','Training & Mechanics','RL method that ranks groups of sampled outputs without a separate value model.','Used to train reasoning models cheaply.'),
array('Instruction Tuning','instruction-tuning','Training & Mechanics','Supervised fine-tuning on instruction and response pairs so the model follows directions.','Turns a base model into a chat model.'),
array('Learning Rate','learning-rate','Training & Mechanics','Step size controlling how much weights change per update.','Too high diverges, too low stalls.'),
array('Learning Rate Schedule','learning-rate-schedule','Training & Mechanics','Plan for changing the learning rate during training.','Warmup then cosine decay.'),
array('LoRA','lora','Training & Mechanics','Low Rank Adaptation fine tuning.','Efficient tuning.'),
array('LoRA (Low-Rank Adaptation)','lora-low-rank-adaptation','Training & Mechanics','A Parameter-Efficient Fine-Tuning (PEFT) technique that freezes base model weights and injects trainable rank decomposition matrices.','Efficiently fine-tuning 70B models on single GPUs.'),
array('Loss Function','loss-function','Training & Mechanics','A mathematical metric evaluating how far a model\'s prediction is from the actual ground truth during training.','Cross-entropy loss, Mean Squared Error.'),
array('Memorization','memorization','Training & Mechanics','Model reproducing training examples verbatim rather than generalizing.','A copyright and privacy risk.'),
array('Mixed Precision Training','mixed-precision-training','Training & Mechanics','Using lower precision numbers such as bf16 to speed training and cut memory.','Standard on modern GPUs.'),
array('Optimizer','optimizer','Training & Mechanics','Algorithm that applies gradients to update weights.','Adam, AdamW, Muon.'),
array('Overfitting','overfitting','Training & Mechanics','A modeling error where an AI performs exceptionally well on training data but poorly on unseen test data due to memorizing noise.','Model failing on real-world validation data.'),
array('Parameters','parameters','Training & Mechanics','The internal variables (weights and biases) that a model learns from data during training, often measured in billions (e.g., 70B parameters).','7B, 70B, 405B parameters.'),
array('PEFT','peft','Training & Mechanics','Parameter Efficient Fine Tuning.','LoRA is PEFT.'),
array('Post-Training','post-training','Training & Mechanics','All tuning after pre-training that shapes behavior, including instruction tuning and preference optimization.','Where helpfulness and safety are instilled.'),
array('PPO (Proximal Policy Optimization)','ppo-proximal-policy-optimization','Training & Mechanics','Reinforcement learning algorithm commonly used in RLHF.','Classic RLHF optimizer.'),
array('Pre-training','pre-training','Training & Mechanics','The initial phase of training an AI model on a massive unlabelled dataset to learn general features and language syntax.','Training an LLM on web scrape data.'),
array('Pruning','pruning','Training & Mechanics','The practice of removing non-essential weights or neurons from a neural network to reduce size and speed up execution.','Model compression for mobile deployment.'),
array('QLoRA','qlora','Training & Mechanics','An extension of LoRA that quantizes the base model to 4-bit precision, enabling fine-tuning on consumer-grade hardware.','Fine-tuning LLMs on a desktop GPU.'),
array('Quantization','quantization','Training & Mechanics','A compression technique that converts model weights from high precision (e.g., FP32 or FP16) to lower precision (e.g., INT8 or INT4) to reduce memory and run on weaker hardware.','GGUF, AWQ, EXL2 quantizations.'),
array('Regularization','regularization','Training & Mechanics','Techniques that discourage overfitting.','Dropout, weight decay, early stopping.'),
array('Reinforcement Learning with Verifiable Rewards (RLVR)','reinforcement-learning-with-verifiable-rewards-rlvr','Training & Mechanics','RL where the reward comes from an objective checker rather than human preference.','Math answers and unit test pass or fail.'),
array('Reward Model','reward-model','Training & Mechanics','A model trained to score outputs by human preference, used to guide reinforcement learning.','The scorer inside RLHF.'),
array('RLAIF (Reinforcement Learning from AI Feedback)','rlaif-reinforcement-learning-from-ai-feedback','Training & Mechanics','An alignment method where AI models evaluate and critique other AI models\' outputs to replace human feedback.','Constitutional AI (Anthropic).'),
array('RLHF','rlhf','Training & Mechanics','Reinforcement Learning from Human Feedback.','Preference training.'),
array('RLHF (Reinforcement Learning from Human Feedback)','rlhf-reinforcement-learning-from-human-feedback','Training & Mechanics','A fine-tuning technique that uses human preference rankings to align model outputs with human intent, safety, and helpfulness.','Aligning raw GPT models into ChatGPT.'),
array('Supervised Fine-Tuning (SFT)','supervised-fine-tuning-sft','Training & Mechanics','Fine-tuning on curated demonstration data.','First stage of most alignment pipelines.'),
array('Tokens per Parameter','tokens-per-parameter','Training & Mechanics','Ratio guiding how much data a model of a given size should see.','Chinchilla optimal training.'),
array('Underfitting','underfitting','Training & Mechanics','A situation where a model is too simple to capture the underlying structure of training data.','Linear model fit to complex non-linear data.'),
array('Weights','weights','Training & Mechanics','Learned numerical values within a neural network that determine the strength of connection between artificial neurons.','Model parameters adjusted during backpropagation.'),
);
