<?php
/**
 * SRJ AI Tools seed data.
 * Generated from SRJ_AI_Tool_Inventory_Tracker.csv, 19 July 2026.
 * 320 tools, 23 categories. Regenerate when the tracker CSV changes.
 * July 24, 2026: added IBM watsonx.governance, Jamf AI Governance, Truyo;
 * ServiceNow row updated for the AI Control Tower expansion. Context: Gartner
 * published its first AI Governance Platforms Magic Quadrant in June 2026.
 * Consumed by srj-ai-tools.php importer. Not loaded on the front end.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
return array(
array('Arize AI','AI Governance & Risk Management Platforms','Arize AI','US','ML observability; LLM tracing; evaluation framework; prompt monitoring','https://arize.com/'),
array('Arthur AI','AI Governance & Risk Management Platforms','Arthur AI','US','Model monitoring and governance; bias mitigation; fairness metrics; compliance reporting','https://www.arthur.ai/'),
array('Credo AI','AI Governance & Risk Management Platforms','Credo AI','US','Purpose-built AI governance; policy packs for EU AI Act, NIST AI RMF; clean interface; fast deployment','https://www.credo.ai/'),
array('Fiddler AI','AI Governance & Risk Management Platforms','Fiddler','US','Model performance management; explainability; bias detection; drift monitoring; LLM observability','https://www.fiddler.ai/'),
array('Holistic AI','AI Governance & Risk Management Platforms','Holistic AI','UK','Bias auditing, risk management, compliance; strong technical depth; mid-market focus','https://www.holisticai.com/'),
array('IBM OpenPages with Watson','AI Governance & Risk Management Platforms','IBM','US','Full GRC platform with AI-specific modules; risk assessment; regulatory mapping; Watson AI automated documentation','https://www.ibm.com/products/openpages'),
array('IBM watsonx.governance','AI Governance & Risk Management Platforms','IBM','US','AI lifecycle governance; model evaluation, monitoring, and documentation; EU AI Act accelerators; named a Leader in Gartner\'s first AI Governance Platforms Magic Quadrant (June 2026)','https://www.ibm.com/products/watsonx-governance'),
array('Jamf AI Governance','AI Governance & Risk Management Platforms','Jamf','US','Native AI control plane for macOS fleets, GA July 1, 2026; discovery and policy enforcement for on-device and cloud AI use on Mac endpoints','https://www.jamf.com/'),
array('Monitaur','AI Governance & Risk Management Platforms','Monitaur','US','Model monitoring with built-in governance; unified monitoring + governance platform','https://www.monitaur.ai/'),
array('OneTrust AI Governance','AI Governance & Risk Management Platforms','OneTrust','US','Privacy-first approach; strong data governance; compliance automation; good for privacy-primary orgs','https://www.onetrust.com/'),
array('ServiceNow AI Governance','AI Governance & Risk Management Platforms','ServiceNow','US','Built into Now Platform; model inventory; risk scoring; approval workflows; AI Control Tower expanded June 2026 to discover, observe, govern, secure, and measure AI deployed across any system; best for existing ServiceNow shops','https://www.servicenow.com/'),
array('Truyo','AI Governance & Risk Management Platforms','Truyo','US','AI governance platform grown out of consent and privacy automation; automated AI inventory, risk assessment, and compliance workflows; recognized in Gartner\'s 2026 AI Governance Platforms Magic Quadrant','https://truyo.com/'),
array('WhyLabs','AI Governance & Risk Management Platforms','WhyLabs','US','Data-centric AI observability; statistical profiling; privacy-preserving monitoring','https://whylabs.ai/'),
array('Apify','Automation & Agents','Apify','Czech Republic','Web scraping platform; actor marketplace; automation; EU-hosted; GDPR','https://apify.com/'),
array('Automation Anywhere','Automation & Agents','Automation Anywhere','US','Intelligent automation platform; AI-powered bots; control room governance; credential vault','https://www.automationanywhere.com/'),
array('Bardeen','Automation & Agents','Bardeen','US','Browser automation AI; web scraping; personal productivity; data exposure risk','https://www.bardeen.ai/'),
array('Blue Prism','Automation & Agents','SS&C Blue Prism','UK','Enterprise RPA; digital workforce; centralized control; UK-hosted; GDPR relevant','https://www.blueprism.com/'),
array('Browse AI','Automation & Agents','Browse AI','Canada','Web scraping automation; data extraction; monitoring; terms-of-service compliance risk','https://www.browse.ai/'),
array('Make (Integromat) AI','Automation & Agents','Make','Czech Republic','Visual automation platform; AI integrations; EU-hosted options; GDPR workflow compliance','https://www.make.com/'),
array('Manus','Automation & Agents','Manus AI','Singapore','Autonomous agent; high decision-influence','https://manus.im/'),
array('Microsoft Power Automate AI','Automation & Agents','Microsoft','US','Enterprise workflow automation; Copilot integration; M365 data access; DLP integration','https://www.microsoft.com/en-us/power-platform/products/power-automate'),
array('n8n','Automation & Agents','n8n','Germany','Workflow automation; agentic actions','https://n8n.io/'),
array('UiPath AI','Automation & Agents','UiPath','US','RPA + AI platform; document understanding; process mining; enterprise automation governance','https://www.uipath.com/'),
array('Zapier AI','Automation & Agents','Zapier','US','Workflow automation with AI; 7000+ app integrations; data flow governance; cross-app exposure','https://zapier.com/ai'),
array('Zapier Central','Automation & Agents','Zapier','US','Workflow automation; agentic actions','https://zapier.com/agents'),
array('01.AI Yi','Chat & General LLMs','01.AI','China','Chinese open-source LLM; Kai-Fu Lee founded; cross-border data review advised','https://www.01.ai/'),
array('AI2 OLMo','Chat & General LLMs','Allen Institute for AI','US','Open-source language model; fully open training data; research transparency; nonprofit','https://allenai.org/'),
array('Aleph Alpha','Chat & General LLMs','Aleph Alpha','Germany','European sovereign LLM; EU-hosted; GDPR-first; multilingual; Luminous model family','https://aleph-alpha.com/'),
array('Apple Intelligence','Chat & General LLMs','Apple','US','On-device LLM; Private Cloud Compute; Apple silicon; minimal data exposure; privacy-first','https://www.apple.com/apple-intelligence/'),
array('Baichuan','Chat & General LLMs','Baichuan AI','China','Chinese open-source LLM; medical and legal fine-tunes; cross-border data review advised','https://www.baichuan-ai.com/'),
array('Cerebras','Chat & General LLMs','Cerebras','US','Wafer-scale AI compute; inference API; on-prem options; high-performance computing','https://www.cerebras.ai/'),
array('Character.ai','Chat & General LLMs','Character.AI','US','Persona chat; HR/appropriate-use risk','https://character.ai/'),
array('ChatGPT','Chat & General LLMs','OpenAI','US','General LLM assistant','https://chatgpt.com/'),
array('Claude','Chat & General LLMs','Anthropic','US','General LLM assistant','https://claude.ai/'),
array('Cohere Coral','Chat & General LLMs','Cohere','Canada','Enterprise chat AI; RAG-native; data privacy focus; Canadian vendor','https://cohere.com/'),
array('Databricks DBRX','Chat & General LLMs','Databricks','US','Open-source general LLM; Mixture-of-Experts; enterprise training; already noted in Data & Analytics','https://www.databricks.com/'),
array('DeepSeek','Chat & General LLMs','DeepSeek AI','China','Open-weight MoE; cross-border data review advised','https://www.deepseek.com/'),
array('Falcon (TII)','Chat & General LLMs','Technology Innovation Institute','UAE','UAE-hosted open-source LLM; sovereign AI; Apache 2.0; Middle East data residency','https://falconllm.tii.ae/'),
array('Fireworks AI','Chat & General LLMs','Fireworks AI','US','Fast inference API; open-source models; enterprise deployment; cost optimization','https://fireworks.ai/'),
array('Gemini','Chat & General LLMs','Google','US','General LLM assistant','https://gemini.google.com/'),
array('Grok','Chat & General LLMs','xAI','US','General LLM assistant','https://grok.com/'),
array('Huawei PanGu','Chat & General LLMs','Huawei','China','Chinese foundation model; cross-border data review advised; Ascend chip optimization','https://www.huawei.com/'),
array('HyperWrite','Chat & General LLMs','HyperWrite','US','Writing assistant + agent','https://www.hyperwriteai.com/'),
array('iFlytek Spark','Chat & General LLMs','iFlytek','China','Chinese voice+language AI; speech recognition; cross-border data review advised','https://www.iflytek.com/'),
array('InternLM (Shanghai AI Lab)','Chat & General LLMs','Shanghai AI Laboratory','China','Chinese open-source LLM; academic research; cross-border data review advised','https://www.shlab.org.cn/'),
array('JAIS (G42 / Inception)','Chat & General LLMs','G42 / Inception','UAE','Arabic-centric LLM; UAE sovereign AI; cultural alignment; Middle East data governance','https://www.g42.ai/'),
array('Janitor AI','Chat & General LLMs','Janitor AI','US','Persona chat; HR/appropriate-use risk','https://janitorai.com/'),
array('Kimi','Chat & General LLMs','Moonshot AI','China','Long-context reasoning; cross-border data review advised','https://www.moonshot.ai/'),
array('Llama (Meta)','Chat & General LLMs','Meta','US','Open-weight model family; often self-hosted','https://www.llama.com/'),
array('LMSYS Arena Models','Chat & General LLMs','LMSYS','US','Model evaluation platform; crowdsourced benchmarking; research transparency; no production use','https://lmarena.ai/'),
array('Microsoft Copilot','Chat & General LLMs','Microsoft','US','Embedded across M365','https://copilot.microsoft.com/'),
array('Mistral / Le Chat','Chat & General LLMs','Mistral AI','France','EU-hosted option; GDPR relevant','https://mistral.ai/'),
array('Notion AI','Chat & General LLMs','Notion Labs','US','Embedded in workspace/knowledge base','https://www.notion.com/product/ai'),
array('NVIDIA Nemotron','Chat & General LLMs','NVIDIA','US','Enterprise LLM family; synthetic data generation; GPU-optimized; self-hosted options','https://www.nvidia.com/en-us/ai-data-science/foundation-models/nemotron/'),
array('Perplexity AI','Chat & General LLMs','Perplexity','US','Search-augmented LLM','https://www.perplexity.ai/'),
array('Pi','Chat & General LLMs','Inflection AI','US','Conversational assistant','https://inflection.ai/'),
array('Poe','Chat & General LLMs','Quora','US','Multi-model aggregator','https://poe.com/'),
array('Replicate','Chat & General LLMs','Replicate','US','Model hosting and inference API; open-source models; community models; content policy','https://replicate.com/'),
array('SambaNova','Chat & General LLMs','SambaNova Systems','US','Enterprise AI hardware+software; DataScale platform; on-prem deployment; sovereign AI','https://sambanova.ai/'),
array('Samsung Gauss','Chat & General LLMs','Samsung','South Korea','On-device LLM; Galaxy AI; personal data processing; Korean vendor; local processing','https://www.samsung.com/'),
array('SaulLM (Saul)','Chat & General LLMs','Saul','France','French legal-domain LLM; specialized training; EU data governance','https://www.counsel.com/'),
array('SenseTime SenseChat','Chat & General LLMs','SenseTime','China','Chinese multimodal LLM; computer vision integration; cross-border data review advised','https://www.sensetime.com/'),
array('Slack AI','Chat & General LLMs','Salesforce','US','Embedded in messaging; message-corpus exposure','https://slack.com/features/ai'),
array('Snowflake Arctic','Chat & General LLMs','Snowflake','US','Enterprise-focused LLM; Apache 2.0 license; data cloud integration; commercial use','https://www.snowflake.com/'),
array('Together AI','Chat & General LLMs','Together AI','US','Decentralized cloud for open models; inference API; model hub; data residency options','https://www.together.ai/'),
array('You.com','Chat & General LLMs','You.com','US','Search-augmented LLM','https://you.com/'),
array('Zoom AI Companion','Chat & General LLMs','Zoom','US','Meeting summarization; recording consent relevant','https://www.zoom.com/en/products/ai-assistant/'),
array('Doubao / Seed (ByteDance)','Chinese Foundation Models','ByteDance','China','Cross-border data review advised','https://www.doubao.com/'),
array('ERNIE (Baidu)','Chinese Foundation Models','Baidu','China','Cross-border data review advised','https://ernie.baidu.com/'),
array('GLM / Z.AI (Zhipu AI)','Chinese Foundation Models','Zhipu AI','China','Cross-border data review advised','https://www.zhipuai.cn/'),
array('Hunyuan (Tencent)','Chinese Foundation Models','Tencent','China','Cross-border data review advised','https://hunyuan.tencent.com/'),
array('MiMo (Xiaomi)','Chinese Foundation Models','Xiaomi','China','Cross-border data review advised','https://www.mi.com/'),
array('MiniMax','Chinese Foundation Models','MiniMax','China','Cross-border data review advised','https://www.minimax.io/'),
array('Qwen / Tongyi Qianwen (Alibaba)','Chinese Foundation Models','Alibaba Cloud','China','Cross-border data review advised','https://qwen.ai/'),
array('AI21 Labs API','Cloud AI Services & Model APIs','AI21 Labs','Israel','Jurassic models; enterprise API; data retention controls; compliance-focused','https://www.ai21.com/'),
array('Amazon SageMaker','Cloud AI Services & Model APIs','Amazon Web Services','US','Full ML lifecycle management; model monitoring; bias detection; explainability tools','https://aws.amazon.com/sagemaker/'),
array('AWS Bedrock','Cloud AI Services & Model APIs','Amazon Web Services','US','Managed foundation model API service; IAM integration; VPC support; model evaluation tools; AgentCore for agent orchestration','https://aws.amazon.com/bedrock/'),
array('Azure Machine Learning','Cloud AI Services & Model APIs','Microsoft','US','MLOps platform; AutoML; model registry; responsible AI toolkit integration','https://azure.microsoft.com/en-us/products/machine-learning'),
array('Azure OpenAI Service','Cloud AI Services & Model APIs','Microsoft','US','OpenAI models in Azure regions; enterprise content filtering; Entra ID integration; data residency controls','https://azure.microsoft.com/en-us/products/ai-services/openai-service'),
array('Cohere API','Cloud AI Services & Model APIs','Cohere','Canada','Enterprise-focused LLM API; strong on data privacy; RAG-optimized; multi-language support','https://docs.cohere.com/'),
array('Google Vertex AI','Cloud AI Services & Model APIs','Google Cloud','US','Unified ML platform; Model Garden; AutoML; MLOps lifecycle; BigQuery integration; TPU support','https://cloud.google.com/vertex-ai'),
array('IBM watsonx','Cloud AI Services & Model APIs','IBM','US','Enterprise AI platform; watsonx.governance for agent inventory, behavior monitoring, hallucination detection; model-agnostic','https://www.ibm.com/watsonx'),
array('NVIDIA NIM','Cloud AI Services & Model APIs','NVIDIA','US','Inference microservices for deploying foundation models; enterprise GPU optimization; self-hosted options','https://build.nvidia.com/'),
array('Anthropic Console','Coding & Developer Tools','Anthropic','US','API management console; prompt testing; evaluation tools; usage monitoring; cost controls','https://console.anthropic.com/'),
array('AutoGen (Microsoft)','Coding & Developer Tools','Microsoft','US','Multi-agent conversation framework; agent orchestration; code generation; Microsoft Research','https://microsoft.github.io/autogen/'),
array('Bolt.new','Coding & Developer Tools','StackBlitz','US','App generation','https://bolt.new/'),
array('Chroma','Coding & Developer Tools','Chroma','US','Open-source embedding database; local-first; lightweight RAG; self-hosted option','https://www.trychroma.com/'),
array('Claude Code','Coding & Developer Tools','Anthropic','US','Agentic coding; source-code exposure','https://www.anthropic.com/claude-code'),
array('Comet ML','Coding & Developer Tools','Comet','US','ML experiment management; model monitoring; production tracking; team collaboration','https://www.comet.com/'),
array('CrewAI','Coding & Developer Tools','CrewAI','US','Multi-agent framework; agent collaboration; task delegation; emerging governance patterns','https://www.crewai.com/'),
array('Cursor','Coding & Developer Tools','Anysphere','US','AI IDE; source-code exposure','https://cursor.com/'),
array('Dify','Coding & Developer Tools','Dify','China','LLM app development platform; workflow orchestration; open-source; cross-border data review advised','https://dify.ai/'),
array('DSPy','Coding & Developer Tools','Stanford NLP','US','Prompt optimization framework; Stanford research; systematic prompt engineering; reproducibility','https://github.com/stanford-oval/storm'),
array('Flowise','Coding & Developer Tools','Flowise','Open Source','Visual LLM workflow builder; low-code RAG; self-hosted; no-code agent building','https://flowiseai.com/'),
array('GitHub Copilot','Coding & Developer Tools','Microsoft/GitHub','US','Code completion; source-code exposure','https://github.com/features/copilot'),
array('Google AI Studio','Coding & Developer Tools','Google','US','Model prototyping','https://aistudio.google.com/'),
array('Hugging Face','Coding & Developer Tools','Hugging Face','US','Model hub; supply-chain/AIBOM relevant','https://huggingface.co/'),
array('LangChain','Coding & Developer Tools','LangChain','US','LLM application framework; agent orchestration; supply-chain risk; rapid breaking changes','https://www.langchain.com/'),
array('LlamaIndex','Coding & Developer Tools','LlamaIndex','US','RAG framework; data connectors; indexing strategies; enterprise RAG governance','https://www.llamaindex.ai/'),
array('Lovable','Coding & Developer Tools','Lovable','Sweden','App generation','https://lovable.dev/'),
array('Neptune.ai','Coding & Developer Tools','Neptune','Poland','ML metadata store; experiment tracking; model registry; EU-hosted options','https://neptune.ai/'),
array('OpenAI API / GPT models','Coding & Developer Tools','OpenAI','US','Direct API; usage-based cost escalation risk','https://platform.openai.com/'),
array('OpenAI Playground / Dashboard','Coding & Developer Tools','OpenAI','US','API testing environment; fine-tuning; usage tracking; team management; cost escalation risk','https://platform.openai.com/playground'),
array('Pinecone','Coding & Developer Tools','Pinecone','US','Vector database; RAG infrastructure; data residency options; enterprise security','https://www.pinecone.io/'),
array('Relevance AI','Coding & Developer Tools','Relevance AI','Australia','No-code AI workforce; agent teams; task automation; APAC data residency','https://relevanceai.com/'),
array('Replit Agent','Coding & Developer Tools','Replit','US','Agentic coding; source-code exposure','https://replit.com/'),
array('Stack AI','Coding & Developer Tools','Stack AI','US','No-code AI app builder; enterprise deployment; workflow automation; data connector governance','https://www.stack-ai.com/'),
array('Tabnine','Coding & Developer Tools','Tabnine','Israel','Code completion; self-host option','https://www.tabnine.com/'),
array('v0 (Vercel)','Coding & Developer Tools','Vercel','US','UI generation','https://v0.dev/'),
array('Voiceflow','Coding & Developer Tools','Voiceflow','Canada','Conversational AI design; voice/chat agent builder; enterprise team features','https://www.voiceflow.com/'),
array('Weaviate','Coding & Developer Tools','Weaviate','Netherlands','Open-source vector DB; GraphQL interface; EU-hosted; GDPR; hybrid search','https://weaviate.io/'),
array('Weights & Biases','Coding & Developer Tools','Weights & Biases','US','ML experiment tracking; model registry; artifact lineage; MLOps governance','https://wandb.ai/'),
array('Windsurf','Coding & Developer Tools','Cognition','US','AI IDE; source-code exposure','https://cognition.ai/'),
array('Alteryx AI','Data & Analytics AI','Alteryx','US','Analytics automation with AI; data blending; workflow governance; self-service analytics risk','https://www.alteryx.com/'),
array('Databricks AI / DBRX','Data & Analytics AI','Databricks','US','Lakehouse AI; DBRX open model; MLflow governance; Unity Catalog data governance; strong lineage tracking','https://www.databricks.com/'),
array('Dataiku','Data & Analytics AI','Dataiku','France','Collaborative data science platform; MLOps; governance workflows; EU-hosted options; GDPR relevant','https://www.dataiku.com/'),
array('Palantir AIP','Data & Analytics AI','Palantir','US','Enterprise AI platform; Ontology-based governance; defense/intel focus; high-stakes decision influence','https://www.palantir.com/'),
array('Snowflake Cortex','Data & Analytics AI','Snowflake','US','Native AI in data cloud; LLM functions; vector search; data residency controls; governance via Snowflake Horizon','https://www.snowflake.com/'),
array('Tableau AI (Einstein)','Data & Analytics AI','Salesforce','US','BI embedded AI; natural language queries; CRM data integration; Trust Layer governance','https://www.tableau.com/products/tableau-ai'),
array('CheggMate','Education & Research AI','Chegg','US','Study AI assistant; academic help; student data; content accuracy; honor code implications','https://www.chegg.com/'),
array('Grammarly for Education','Education & Research AI','Grammarly','US','Institutional writing support; student data; FERPA compliance; generative AI features','https://www.grammarly.com/'),
array('Khanmigo (Khan Academy)','Education & Research AI','Khan Academy','US','Educational AI tutor; student interaction data; COPPA compliance; pedagogical bias','https://www.khanacademy.org/'),
array('Turnitin AI Detection','Education & Research AI','Turnitin','US','AI writing detection; academic integrity; false positive risk; student data privacy (FERPA)','https://www.turnitin.com/'),
array('Cohere Command R+','Emerging / Frontier AI','Cohere','Canada','Enterprise RAG-optimized model; tool use; autonomous retrieval; data grounding verification','https://cohere.com/command'),
array('Computer Use (Anthropic)','Emerging / Frontier AI','Anthropic','US','Computer control agent; desktop automation; system access; high-privilege operation risk','https://www.anthropic.com/news/3-5-models-and-computer-use'),
array('Devin (Cognition)','Emerging / Frontier AI','Cognition','US','Autonomous software engineer; full codebase access; high decision-influence; security critical','https://cognition.ai/'),
array('Figure AI','Emerging / Frontier AI','Figure AI','US','Humanoid robotics AI; physical world interaction; safety-critical; embodied AI governance','https://www.figure.ai/'),
array('Mistral Large 2','Emerging / Frontier AI','Mistral AI','France','Advanced EU-hosted LLM; multilingual; GDPR-first design; sovereign AI option','https://mistral.ai/'),
array('Operator (OpenAI)','Emerging / Frontier AI','OpenAI','US','Autonomous web agent; browser control; credential exposure; action authorization risk','https://openai.com/operator/'),
array('Physical Intelligence (pi0)','Emerging / Frontier AI','Physical Intelligence','US','General-purpose robot AI; physical task learning; safety-critical; emerging governance standards','https://www.physicalintelligence.company/'),
array('Tesla Optimus','Emerging / Frontier AI','Tesla','US','Humanoid robot; factory automation; physical safety; worker interaction; liability','https://www.tesla.com/'),
array('Aisera','Enterprise AI Platforms & Agent Orchestration','Aisera','US','AI service management platform; autonomous service desk; enterprise governance features','https://aisera.com/'),
array('Cognigy','Enterprise AI Platforms & Agent Orchestration','Cognigy','Germany','Conversational AI platform for customer service; GDPR-compliant; EU-hosted options','https://www.cognigy.com/'),
array('Decagon','Enterprise AI Platforms & Agent Orchestration','Decagon','US','Customer support agent platform; omnichannel; model-agnostic; Watchtower monitoring','https://decagon.ai/'),
array('Glean','Enterprise AI Platforms & Agent Orchestration','Glean','US','Enterprise knowledge search AI; 100+ connectors; permission-aware retrieval; data access governance','https://www.glean.com/'),
array('Kore.ai','Enterprise AI Platforms & Agent Orchestration','Kore.ai','US','Enterprise agentic AI platform; multi-agent orchestration; comprehensive governance dashboard with audit logs, RBAC, and guardrails; 400+ Fortune 2000 customers','https://kore.ai/'),
array('Moveworks','Enterprise AI Platforms & Agent Orchestration','Moveworks','US','Employee support automation; IT service desk agent; enterprise-grade access controls','https://www.moveworks.com/'),
array('Sierra','Enterprise AI Platforms & Agent Orchestration','Sierra','US','Conversational AI for customer experience; enterprise agent platform','https://sierra.ai/'),
array('Vellum','Enterprise AI Platforms & Agent Orchestration','Vellum','US','Personal AI assistant; on-device Mac app or cloud; cross-app memory; privacy-first design','https://www.vellum.ai/'),
array('Oracle Fusion AI','ERP & Business Application AI','Oracle','US','Embedded AI across ERP, HCM, SCM; autonomous database; enterprise data governance','https://www.oracle.com/'),
array('SAP Joule','ERP & Business Application AI','SAP','Germany','ERP copilot across S/4HANA, SuccessFactors, Ariba; Joule Studio for custom agents; Knowledge Graph integration; ledger-modification risk','https://www.sap.com/'),
array('ServiceNow Now Assist','ERP & Business Application AI','ServiceNow','US','ITSM/HRSD embedded AI; workflow automation; enterprise process governance','https://www.servicenow.com/'),
array('Workday AI','ERP & Business Application AI','Workday','US','HR and finance AI; skills-based talent; predictive analytics; sensitive HR data exposure','https://www.workday.com/'),
array('AlphaSense','Finance & Legal AI','AlphaSense','US','Market intelligence AI; financial research; insider information risk; MNPI controls needed','https://www.alpha-sense.com/'),
array('Bloomberg GPT','Finance & Legal AI','Bloomberg','US','Finance-specific LLM; market data integration; proprietary data handling; trading decision risk','https://www.bloomberg.com/'),
array('CoCounsel (Casetext)','Finance & Legal AI','Thomson Reuters','US','Legal research AI; litigation support; Westlaw integration; attorney work product risk','https://www.thomsonreuters.com/'),
array('Harvey AI','Finance & Legal AI','Harvey','US','Legal AI assistant; contract drafting; case research; law firm data exposure; privilege concerns','https://www.harvey.ai/'),
array('Kira Systems','Finance & Legal AI','Litera','US','Contract analysis AI; legal document review; attorney-client privilege risk; confidential data','https://www.litera.com/'),
array('Vanta','Finance & Legal AI','Vanta','US','Security compliance automation; SOC 2, ISO 27001; continuous monitoring; audit automation','https://www.vanta.com/'),
array('Epic AI (SlicerDicer, etc.)','Healthcare & Life Sciences AI','Epic Systems','US','Clinical decision support; patient data exposure; HIPAA critical; FDA SaMD considerations','https://www.epic.com/'),
array('Google Med-PaLM / MedLM','Healthcare & Life Sciences AI','Google','US','Medical LLM; clinical reasoning; healthcare data; HIPAA BAA required; diagnostic liability','https://sites.research.google/med-palm/'),
array('Insilico Medicine','Healthcare & Life Sciences AI','Insilico Medicine','Hong Kong','Drug discovery AI; molecular design; IP generation; cross-border data (China/HK)','https://insilico.com/'),
array('Merative (formerly Watson Health)','Healthcare & Life Sciences AI','Merative','US','Healthcare data analytics; clinical AI; population health; PHI governance','https://www.merative.com/'),
array('Tempus AI','Healthcare & Life Sciences AI','Tempus','US','Precision medicine AI; genomic data; clinical trial matching; genetic privacy (GINA)','https://www.tempus.com/'),
array('Beamery','HR & Talent AI','Beamery','UK','Talent lifecycle management AI; skills ontology; DEI analytics; UK-hosted; GDPR relevant','https://beamery.com/'),
array('Eightfold AI','HR & Talent AI','Eightfold','US','Talent intelligence platform; skills matching; DEI bias risk; high-stakes employment decisions','https://eightfold.ai/'),
array('HireVue','HR & Talent AI','HireVue','US','Video interviewing AI; facial analysis controversy; algorithmic hiring bias; regulatory scrutiny','https://www.hirevue.com/'),
array('LinkedIn Recruiter AI','HR & Talent AI','Microsoft/LinkedIn','US','Talent acquisition AI; candidate matching; bias risk in hiring; GDPR for EU candidates','https://business.linkedin.com/talent-solutions/recruiter'),
array('Paradox (Olivia)','HR & Talent AI','Paradox','US','Conversational recruiting AI; candidate screening; automated scheduling; hiring bias risk','https://www.paradox.ai/'),
array('Adobe Express AI','Image & Graphic Design','Adobe','US','Lightweight design AI; quick content creation; Adobe Firefly integration; commercial-safe','https://www.adobe.com/express/'),
array('Adobe Firefly','Image & Graphic Design','Adobe','US','Image generation; commercial-safe training claim','https://www.adobe.com/products/firefly.html'),
array('Blender AI Add-ons','Image & Graphic Design','Blender Foundation','Netherlands','3D creation AI plugins; open-source; local processing; model provenance varies by plugin','https://www.blender.org/'),
array('Canva AI','Image & Graphic Design','Canva','Australia','Design generation','https://www.canva.com/ai-assistant/'),
array('Clipdrop (Stability AI)','Image & Graphic Design','Stability AI','UK','Image editing AI suite; Stability AI ecosystem; open-weight tools; commercial licensing','https://clipdrop.co/'),
array('DALL-E (OpenAI)','Image & Graphic Design','OpenAI','US','Image generation; IP provenance relevant','https://openai.com/dall-e-3/'),
array('DeepAI','Image & Graphic Design','DeepAI','US','Image generation','https://deepai.org/'),
array('Figma AI','Image & Graphic Design','Figma','US','Design AI; auto-layout; content generation; design system governance; Adobe acquisition context','https://www.figma.com/'),
array('Freepik AI','Image & Graphic Design','Freepik','Spain','Stock image AI generation; commercial licensing; EU-hosted; content moderation','https://www.freepik.com/'),
array('Ideogram','Image & Graphic Design','Ideogram','Canada','Text-in-image generation; typography AI; commercial use; IP and copyright considerations','https://ideogram.ai/'),
array('Jasper Art','Image & Graphic Design','Jasper','US','Marketing image generation; brand asset creation; commercial use; same vendor as Jasper copy','https://www.jasper.ai/art'),
array('Krita AI','Image & Graphic Design','Krita Foundation','Netherlands','Open-source digital art; local AI plugins; no cloud dependency; community governance','https://krita.org/'),
array('Leonardo.ai','Image & Graphic Design','Canva','Australia','Image generation','https://leonardo.ai/'),
array('Microsoft Designer','Image & Graphic Design','Microsoft','US','Image/design generation','https://designer.microsoft.com/'),
array('Midjourney','Image & Graphic Design','Midjourney','US','Image generation; IP provenance relevant','https://www.midjourney.com/'),
array('Miro AI','Image & Graphic Design','Miro','US','Collaborative whiteboard AI; diagram generation; sticky note synthesis; creative IP risk','https://miro.com/'),
array('Photoroom','Image & Graphic Design','Photoroom','France','AI photo editing; background removal; e-commerce focus; EU data handling','https://www.photoroom.com/'),
array('Recraft','Image & Graphic Design','Recraft','UK','Vector image generation; brand consistency; commercial design; UK-hosted','https://www.recraft.ai/'),
array('Remove.bg','Image & Graphic Design','Canva','Australia','Image processing','https://www.remove.bg/'),
array('Sketch AI','Image & Graphic Design','Sketch','Netherlands','Design tool AI; macOS native; local processing option; EU design data','https://www.sketch.com/'),
array('Stable Diffusion','Image & Graphic Design','Stability AI','UK','Open-weight image model','https://stability.ai/stable-image'),
array('Asana AI','Notes, Knowledge & Meetings','Asana','US','Work management AI; goal tracking; team productivity analytics; data residency options','https://asana.com/'),
array('Avoma','Notes, Knowledge & Meetings','Avoma','US','Meeting intelligence AI; conversation analytics; coaching; revenue team data','https://www.avoma.com/'),
array('Box AI','Notes, Knowledge & Meetings','Box','US','Enterprise content AI; metadata; governance; compliance; retention policies','https://www.box.com/'),
array('Cisco Webex AI','Notes, Knowledge & Meetings','Cisco','US','Meeting intelligence; real-time translation; noise removal; enterprise security','https://www.cisco.com/'),
array('ClickUp AI','Notes, Knowledge & Meetings','ClickUp','US','All-in-one productivity AI; document generation; task automation; broad data access','https://clickup.com/'),
array('Coda AI','Notes, Knowledge & Meetings','Coda','US','All-in-one doc AI; automation; team data; enterprise governance features','https://coda.io/'),
array('Confluence AI','Notes, Knowledge & Meetings','Atlassian','Australia','Team wiki AI; smart links; automation; Atlassian Cloud governance','https://www.atlassian.com/'),
array('Dropbox AI','Notes, Knowledge & Meetings','Dropbox','US','Cloud storage AI; document summaries; team data; sharing controls','https://www.dropbox.com/'),
array('Fathom','Notes, Knowledge & Meetings','Fathom','US','Meeting notetaker AI; auto-summaries; CRM sync; consent and privacy','https://fathom.video/'),
array('Fireflies.ai','Notes, Knowledge & Meetings','Fireflies.ai','US','Meeting transcription; consent relevant','https://fireflies.ai/'),
array('Gong','Notes, Knowledge & Meetings','Gong','US','Revenue intelligence AI; call analysis; deal coaching; sensitive sales data exposure','https://www.gong.io/'),
array('Google Drive AI','Notes, Knowledge & Meetings','Google','US','Cloud storage AI; Gemini integration; Workspace data; sharing governance','https://workspace.google.com/'),
array('Google Meet AI','Notes, Knowledge & Meetings','Google','US','Meeting summaries; live captions; note-taking; Google Workspace data','https://workspace.google.com/products/meet/'),
array('Grain','Notes, Knowledge & Meetings','Grain','US','Meeting recording AI; highlight clips; CRM integration; consent and sharing','https://grain.com/'),
array('Logseq AI','Notes, Knowledge & Meetings','Logseq','Open Source','Open-source knowledge base; local-first; graph database; privacy-focused','https://logseq.com/'),
array('Mem','Notes, Knowledge & Meetings','Mem Labs','US','Personal knowledge base','https://get.mem.ai/'),
array('Microsoft Teams AI','Notes, Knowledge & Meetings','Microsoft','US','Meeting recaps; intelligent recap; Copilot integration; M365 data exposure','https://www.microsoft.com/en-us/microsoft-teams/premium'),
array('Monday.com AI','Notes, Knowledge & Meetings','monday.com','Israel','Work OS AI; project automation; cross-functional data; Israeli data transfer considerations','https://monday.com/'),
array('NotebookLM','Notes, Knowledge & Meetings','Google','US','Document grounding; ingests uploaded corpora','https://notebooklm.google.com/'),
array('Notion Q&A','Notes, Knowledge & Meetings','Notion Labs','US','Knowledge base AI Q&A; workspace corpus access; permission-aware but broad exposure risk','https://www.notion.com/product/ai'),
array('Obsidian AI','Notes, Knowledge & Meetings','Obsidian','Canada','Local-first knowledge AI; plugins; privacy-focused; no cloud dependency','https://obsidian.md/'),
array('Otter.ai','Notes, Knowledge & Meetings','Otter.ai','US','Meeting transcription; consent relevant','https://otter.ai/'),
array('Read.ai','Notes, Knowledge & Meetings','Read','US','Meeting analytics AI; engagement scoring; wellness insights; behavioral data privacy','https://www.read.ai/'),
array('SharePoint AI','Notes, Knowledge & Meetings','Microsoft','US','Enterprise content AI; Copilot integration; M365 governance; DLP','https://www.microsoft.com/en-us/microsoft-365/sharepoint/collaboration'),
array('Supernormal','Notes, Knowledge & Meetings','Supernormal','US','Meeting notes AI; action items; CRM sync; team productivity data','https://supernormal.com/'),
array('tl;dv','Notes, Knowledge & Meetings','tl;dv','Germany','Meeting recorder AI; timestamped notes; EU-hosted; GDPR; consent management','https://tldv.io/'),
array('Trello AI (Atlassian)','Notes, Knowledge & Meetings','Atlassian','Australia','Project management AI; workflow automation; team data exposure; Atlassian Cloud governance','https://www.atlassian.com/'),
array('Hugging Face Transformers','Open Source & Self-Hosted Models','Hugging Face','US','Model hub and inference library; supply-chain/AIBOM critical; model card verification; security scanning','https://huggingface.co/'),
array('llama.cpp','Open Source & Self-Hosted Models','Georgi Gerganov','Open Source','Lightweight LLM inference; C++ implementation; edge deployment; model provenance tracking','https://github.com/ggml-org/llama.cpp'),
array('Ollama','Open Source & Self-Hosted Models','Ollama','US','Local LLM runner; self-hosted; no data exfiltration; model supply-chain verification needed','https://ollama.com/'),
array('PyTorch','Open Source & Self-Hosted Models','Meta / Linux Foundation','US','Deep learning framework; model checkpoint governance; TorchServe deployment; research-to-production lineage','https://pytorch.org/'),
array('TensorFlow / Keras','Open Source & Self-Hosted Models','Google','US','ML framework; model serialization risks; custom model governance; TensorFlow Extended (TFX) for MLOps','https://www.tensorflow.org/'),
array('vLLM','Open Source & Self-Hosted Models','UC Berkeley / vLLM Team','US','High-throughput inference engine; open-source; self-hosted; no external data sharing','https://github.com/vllm-project/vllm'),
array('Connected Papers','Search, Research, Translation & Other','Connected Papers','Israel','Visual paper graph; literature discovery; academic research; Israeli vendor','https://www.connectedpapers.com/'),
array('Consensus','Search, Research, Translation & Other','Consensus','US','Research search','https://consensus.app/'),
array('DeepL','Search, Research, Translation & Other','DeepL','Germany','Translation; EU-hosted','https://www.deepl.com/'),
array('Elicit','Search, Research, Translation & Other','Elicit','US','Research assistant AI; paper analysis; systematic review; academic integrity','https://elicit.com/'),
array('Groq','Search, Research, Translation & Other','Groq','US','Inference acceleration','https://groq.com/'),
array('Lokalise AI','Search, Research, Translation & Other','Lokalise','UK','Localization AI; continuous translation; developer workflow; UK-hosted','https://lokalise.com/'),
array('Perplexity Enterprise Pro','Search, Research, Translation & Other','Perplexity','US','Enterprise search AI; internal knowledge search; data indexing; SSO; audit logs','https://www.perplexity.ai/'),
array('Phrase (Memsource)','Search, Research, Translation & Other','Phrase','Czech Republic','Enterprise localization AI; TMS; machine translation; EU-hosted; GDPR','https://phrase.com/'),
array('ResearchRabbit','Search, Research, Translation & Other','ResearchRabbit','US','Research discovery AI; paper recommendations; collaboration features; academic data','https://www.researchrabbit.ai/'),
array('Salesforce Einstein / Agentforce','Search, Research, Translation & Other','Salesforce','US','CRM-embedded AI + agents','https://www.salesforce.com/agentforce/'),
array('Scite','Search, Research, Translation & Other','Scite','US','Smart citation analysis; claim verification; research quality; academic trust','https://scite.ai/'),
array('Semantic Scholar','Search, Research, Translation & Other','Allen Institute for AI','US','Academic search AI; paper summaries; citation graphs; nonprofit research focus','https://allenai.org/'),
array('Smartcat','Search, Research, Translation & Other','Smartcat','US','Translation management AI; CAT tool; vendor marketplace; translation memory governance','https://www.smartcat.com/'),
array('Unbabel','Search, Research, Translation & Other','Unbabel','Portugal','AI-human translation; quality estimation; enterprise localization; EU vendor','https://unbabel.com/'),
array('Wayground','Search, Research, Translation & Other','Wayground','US','Education tooling','https://wayground.com/'),
array('You.com Enterprise','Search, Research, Translation & Other','You.com','US','Private search AI; no tracking; enterprise deployment; data privacy focus','https://you.com/business'),
array('CrowdStrike Charlotte AI','Security & Identity AI','CrowdStrike','US','Security operations AI; threat detection; autonomous response; high-privilege access','https://www.crowdstrike.com/'),
array('Darktrace','Security & Identity AI','Darktrace','UK','Self-learning AI security; anomaly detection; autonomous response; UK-hosted; GDPR relevant','https://www.darktrace.com/'),
array('Okta AI','Security & Identity AI','Okta','US','Identity AI; risk-based authentication; privileged access; identity threat detection','https://www.okta.com/'),
array('Palo Alto Networks Precision AI','Security & Identity AI','Palo Alto Networks','US','Network security AI; Zero Trust integration; autonomous threat response; critical infrastructure','https://www.paloaltonetworks.com/'),
array('SentinelOne Purple AI','Security & Identity AI','SentinelOne','US','Endpoint security AI; autonomous response; XDR platform; kill-switch capabilities','https://www.sentinelone.com/'),
array('Zscaler AI','Security & Identity AI','Zscaler','US','Cloud security AI; SSE platform; data loss prevention; AI traffic inspection','https://www.zscaler.com/'),
array('Beautiful.ai','Slides & Presentations','Beautiful.ai','US','Presentation generation','https://www.beautiful.ai/'),
array('Decktopus','Slides & Presentations','Decktopus','US','AI presentation maker; automated design; content generation; data exposure','https://www.decktopus.com/'),
array('Gamma','Slides & Presentations','Gamma','US','Presentation generation','https://gamma.app/'),
array('Pitch AI','Slides & Presentations','Pitch','Germany','Presentation software AI; collaboration; template generation; EU-hosted','https://pitch.com/'),
array('Presentations.AI','Slides & Presentations','Presentations.AI','US','Text-to-presentation AI; automated layouts; brand templates; content governance','https://www.presentations.ai/'),
array('SlidesAI','Slides & Presentations','SlidesAI','India','Presentation generation','https://www.slidesai.io/'),
array('Tome','Slides & Presentations','Tome','US','AI storytelling; presentation generation; narrative design; creative IP',''),
array('2short.ai','Video Generation & Editing','2short','US','YouTube shorts AI; clip extraction; content automation; platform dependency','https://2short.ai/'),
array('CapCut','Video Generation & Editing','ByteDance','China','Video editing; cross-border data review advised','https://www.capcut.com/'),
array('Captions AI','Video Generation & Editing','Captions','US','AI video editing; eye contact correction; dubbing; likeness manipulation consent','https://www.captions.ai/'),
array('Colossyan','Video Generation & Editing','Colossyan','UK','AI video avatars; enterprise training; consent management; UK-hosted','https://www.colossyan.com/'),
array('D-ID','Video Generation & Editing','D-ID','Israel','Talking head AI; photo animation; likeness rights; deepfake risk; Israeli vendor','https://www.d-id.com/'),
array('DaVinci Resolve AI','Video Generation & Editing','Blackmagic Design','Australia','Professional video AI; color grading; facial recognition; local processing option','https://www.blackmagicdesign.com/'),
array('Descript','Video Generation & Editing','Descript','US','Audio/video editing + voice cloning','https://www.descript.com/'),
array('Elai.io','Video Generation & Editing','Elai','US','AI avatar video; text-to-video; multilingual; enterprise training; consent','https://elai.io/'),
array('Filmora AI','Video Generation & Editing','Wondershare','China','Video editing','https://filmora.wondershare.com/'),
array('Final Cut Pro AI','Video Generation & Editing','Apple','US','Mac video editing AI; on-device processing; privacy-first; Apple silicon optimization','https://www.apple.com/final-cut-pro/'),
array('Fliki','Video Generation & Editing','Fliki','US','Video + voice generation','https://fliki.ai/'),
array('Hailuo AI (MiniMax)','Video Generation & Editing','MiniMax','China','Video generation; cross-border data review advised; same vendor as MiniMax LLM','https://www.minimax.io/'),
array('Headliner','Video Generation & Editing','Headliner','US','Podcast/video promotion; audiogram generation; social media; content marketing','https://www.headliner.app/'),
array('HeyGen','Video Generation & Editing','HeyGen','US','AI avatars; likeness/consent risk','https://www.heygen.com/'),
array('Hour One','Video Generation & Editing','Hour One','Israel','AI avatar video; virtual presenters; enterprise video; likeness consent; Israeli vendor','https://hourone.ai/'),
array('iMovie AI','Video Generation & Editing','Apple','US','Consumer video editing; trailer templates; on-device; Apple privacy','https://www.apple.com/imovie/'),
array('InShot AI','Video Generation & Editing','InShot','China','Mobile video editing AI; social content; cross-border data review advised','https://inshot.com/'),
array('InVideo','Video Generation & Editing','InVideo','India','Video generation','https://invideo.io/'),
array('Kling AI (Kuaishou)','Video Generation & Editing','Kuaishou','China','Video generation model; cross-border data review advised; content moderation; Chinese vendor','https://www.kuaishou.com/'),
array('Krea AI','Video Generation & Editing','Krea','US','Real-time video generation; creative tool; content moderation; emerging platform','https://www.krea.ai/'),
array('Loom AI','Video Generation & Editing','Loom','US','Async video AI; auto-chapters; summaries; transcription; Atlassian acquisition context','https://www.loom.com/'),
array('Luma AI','Video Generation & Editing','Luma AI','US','3D/video generation','https://lumalabs.ai/'),
array('Lumen5','Video Generation & Editing','Lumen5','Canada','Video generation','https://lumen5.com/'),
array('Microsoft Clipchamp AI','Video Generation & Editing','Microsoft','US','Video editing AI; M365 integration; auto-caption; text-to-speech; enterprise data','https://clipchamp.com/'),
array('Munch','Video Generation & Editing','Munch','Israel','Content repurposing AI; auto-editing; social clips; trend analysis; Israeli vendor','https://www.getmunch.com/'),
array('OpusClip','Video Generation & Editing','OpusClip','US','Video repurposing','https://www.opus.pro/'),
array('Pictory','Video Generation & Editing','Pictory','US','Video generation','https://pictory.ai/'),
array('Pika Labs','Video Generation & Editing','Pika Labs','US','Video generation; meme/creative focus; content policy; IP provenance','https://pika.art/'),
array('Premiere Pro AI (Adobe)','Video Generation & Editing','Adobe','US','Professional video AI; generative extend; color match; commercial-safe training','https://www.adobe.com/products/premiere.html'),
array('Repurpose.io','Video Generation & Editing','Repurpose','US','Content distribution automation; multi-platform; workflow automation; API access','https://repurpose.io/'),
array('Runway','Video Generation & Editing','Runway','US','Video generation','https://runwayml.com/'),
array('Sora (OpenAI)','Video Generation & Editing','OpenAI','US','Video generation; provenance/disclosure relevant','https://sora.com/'),
array('Splice','Video Generation & Editing','Splice','US','Mobile video editing; music licensing; content creation; GoPro ownership','https://splice.com/'),
array('Submagic','Video Generation & Editing','Submagic','France','Auto-caption AI; video subtitles; emoji/sticker automation; EU vendor','https://www.submagic.co/'),
array('Synthesia','Video Generation & Editing','Synthesia','UK','AI avatars; likeness/consent risk','https://www.synthesia.io/'),
array('Veed.io AI','Video Generation & Editing','Veed','UK','Online video editing AI; auto-subtitle; text-to-speech; UK-hosted','https://www.veed.io/'),
array('Videoleap','Video Generation & Editing','Lightricks','Israel','Mobile video editing AI; effects; templates; Israeli vendor','https://www.lightricks.com/'),
array('Vidu (Tsinghua / Shengshu)','Video Generation & Editing','Shengshu Technology','China','Video generation model; academic spin-off; cross-border data review advised','https://www.vidu.studio/'),
array('Vizard AI','Video Generation & Editing','Vizard','US','Video repurposing; auto-clipping; social media; content strategy AI','https://vizard.ai/'),
array('Wavve','Video Generation & Editing','Wavve','US','Audio-to-video AI; podcast clips; waveform videos; social media content','https://wavve.co/'),
array('Wistia','Video Generation & Editing','Wistia','US','Video hosting AI; analytics; marketing video; data privacy; engagement tracking','https://wistia.com/'),
array('Wondershare Virbo','Video Generation & Editing','Wondershare','China','AI avatar video; cross-border data review advised; likeness consent; Chinese vendor','https://virbo.wondershare.com/'),
array('Zeemo','Video Generation & Editing','Zeemo','US','Video captioning AI; translation; subtitle styling; content accessibility','https://zeemo.ai/'),
array('Adobe Podcast AI','Voice & Audio','Adobe','US','Audio enhancement AI; speech enhancement; microphone check; commercial-safe training claim','https://podcast.adobe.com/'),
array('AIVA','Voice & Audio','AIVA Technologies','Luxembourg','Classical music AI composer; copyright assignment; EU-hosted; commercial licensing','https://www.aiva.ai/'),
array('Altered','Voice & Audio','Altered','UK','Professional voice editing; voice morphing; dubbing; consent management; UK-hosted','https://www.altered.ai/'),
array('AssemblyAI','Voice & Audio','AssemblyAI','US','Speech AI API; transcription; summarization; PII redaction; enterprise security','https://www.assemblyai.com/'),
array('Deepgram','Voice & Audio','Deepgram','US','Speech recognition API; real-time transcription; model customization; on-prem option','https://deepgram.com/'),
array('Descript Overdub','Voice & Audio','Descript','US','Voice cloning for editing; consent recording required; deepfake risk; media integrity','https://www.descript.com/'),
array('ElevenLabs','Voice & Audio','ElevenLabs','US','Voice cloning; likeness/consent risk','https://elevenlabs.io/'),
array('Krisp','Voice & Audio','Krisp','US','Audio processing','https://krisp.ai/'),
array('Lovo (Genny)','Voice & Audio','Lovo','US','Voice cloning and synthesis; likeness consent; commercial voiceover; synthetic media disclosure','https://lovo.ai/'),
array('Murf.ai','Voice & Audio','Murf','India','Voice synthesis','https://murf.ai/'),
array('Play.ht','Voice & Audio','PlayAI','US','Voice synthesis',''),
array('Resemble AI','Voice & Audio','Resemble AI','US','Voice cloning; likeness/consent risk','https://www.resemble.ai/'),
array('Respeecher','Voice & Audio','Respeecher','Ukraine','Voice cloning for media; entertainment focus; likeness rights; Ukrainian vendor','https://www.respeecher.com/'),
array('Rev AI','Voice & Audio','Rev','US','Speech-to-text API; transcription; captioning; human + AI hybrid; data confidentiality','https://www.rev.com/'),
array('Soundraw','Voice & Audio','Soundraw','Japan','Royalty-free AI music; commercial license; JASRAC considerations for Japan use','https://soundraw.io/'),
array('Speechmatics','Voice & Audio','Speechmatics','UK','Speech-to-text; real-time translation; accent-agnostic; UK-hosted; GDPR','https://www.speechmatics.com/'),
array('Suno','Voice & Audio','Suno','US','Music generation; IP provenance relevant','https://suno.com/'),
array('Udio','Voice & Audio','Udio','US','AI music generation; copyright risk; likeness in vocals; RIAA litigation context','https://www.udio.com/'),
array('Voicemod','Voice & Audio','Voicemod','Spain','Real-time voice changing; gaming/streaming; content moderation; EU vendor','https://www.voicemod.net/'),
array('Whisper API (OpenAI)','Voice & Audio','OpenAI','US','Speech recognition; transcription; translation; API data retention policy','https://platform.openai.com/docs/guides/speech-to-text'),
array('Anyword','Writing & Editing','Anyword','US','Predictive performance AI copy; marketing optimization; data-driven; performance claims','https://www.anyword.com/'),
array('Clearscope','Writing & Editing','Clearscope','US','Content optimization AI; readability scoring; competitor content analysis','https://www.clearscope.io/'),
array('Copy.ai','Writing & Editing','Copy.ai','US','Marketing copy / GTM workflows','https://www.copy.ai/'),
array('Frase','Writing & Editing','Frase','US','SEO content AI; SERP analysis; competitive data scraping; search algorithm dependency','https://www.frase.io/'),
array('Grammarly','Writing & Editing','Grammarly','US','Reads document text broadly','https://www.grammarly.com/'),
array('Jasper','Writing & Editing','Jasper','US','Marketing copy','https://www.jasper.ai/'),
array('Jasper Campaigns','Writing & Editing','Jasper','US','End-to-end marketing campaigns AI; brand voice; cross-channel content; governance dashboard','https://www.jasper.ai/'),
array('MarketMuse','Writing & Editing','MarketMuse','US','Content strategy AI; topic modeling; site-wide content audit; competitive intelligence','https://www.marketmuse.com/'),
array('QuillBot','Writing & Editing','Course Hero','US','Paraphrasing','https://www.coursehero.com/'),
array('Rytr','Writing & Editing','Rytr','US','Marketing copy','https://rytr.me/'),
array('Surfer SEO','Writing & Editing','Surfer','Poland','SEO optimization AI; content scoring; NLP analysis; EU-hosted options','https://surferseo.com/'),
array('Typeface','Writing & Editing','Typeface','US','Enterprise content AI; brand-customized models; marketing asset generation; high decision-influence','https://www.typeface.ai/'),
array('Wordtune','Writing & Editing','AI21 Labs','Israel','Rewriting','https://www.ai21.com/'),
array('Writer.com','Writing & Editing','Writer','US','Enterprise writing AI; brand governance; style guide enforcement; hallucination detection; PALMYRA models','https://writer.com/'),
array('WriteSonic','Writing & Editing','Writesonic','US','Marketing copy','https://writesonic.com/'),
);
