<?php
/**
 * SRJ AI Tools seed data.
 * Generated from SRJ_AI_Tool_Inventory_Tracker.csv, 19 July 2026.
 * 317 tools, 23 categories. Regenerate when the tracker CSV changes.
 * Consumed by srj-ai-tools.php importer. Not loaded on the front end.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
return array(
array('Arize AI','AI Governance & Risk Management Platforms','Arize AI','US','ML observability; LLM tracing; evaluation framework; prompt monitoring'),
array('Arthur AI','AI Governance & Risk Management Platforms','Arthur AI','US','Model monitoring and governance; bias mitigation; fairness metrics; compliance reporting'),
array('Credo AI','AI Governance & Risk Management Platforms','Credo AI','US','Purpose-built AI governance; policy packs for EU AI Act, NIST AI RMF; clean interface; fast deployment'),
array('Fiddler AI','AI Governance & Risk Management Platforms','Fiddler','US','Model performance management; explainability; bias detection; drift monitoring; LLM observability'),
array('Holistic AI','AI Governance & Risk Management Platforms','Holistic AI','UK','Bias auditing, risk management, compliance; strong technical depth; mid-market focus'),
array('IBM OpenPages with Watson','AI Governance & Risk Management Platforms','IBM','US','Full GRC platform with AI-specific modules; risk assessment; regulatory mapping; Watson AI automated documentation'),
array('Monitaur','AI Governance & Risk Management Platforms','Monitaur','US','Model monitoring with built-in governance; unified monitoring + governance platform'),
array('OneTrust AI Governance','AI Governance & Risk Management Platforms','OneTrust','US','Privacy-first approach; strong data governance; compliance automation; good for privacy-primary orgs'),
array('ServiceNow AI Governance','AI Governance & Risk Management Platforms','ServiceNow','US','Built into Now Platform; model inventory; risk scoring; approval workflows; best for existing ServiceNow shops'),
array('WhyLabs','AI Governance & Risk Management Platforms','WhyLabs','US','Data-centric AI observability; statistical profiling; privacy-preserving monitoring'),
array('Apify','Automation & Agents','Apify','Czech Republic','Web scraping platform; actor marketplace; automation; EU-hosted; GDPR'),
array('Automation Anywhere','Automation & Agents','Automation Anywhere','US','Intelligent automation platform; AI-powered bots; control room governance; credential vault'),
array('Bardeen','Automation & Agents','Bardeen','US','Browser automation AI; web scraping; personal productivity; data exposure risk'),
array('Blue Prism','Automation & Agents','SS&C Blue Prism','UK','Enterprise RPA; digital workforce; centralized control; UK-hosted; GDPR relevant'),
array('Browse AI','Automation & Agents','Browse AI','Canada','Web scraping automation; data extraction; monitoring; terms-of-service compliance risk'),
array('Make (Integromat) AI','Automation & Agents','Make','Czech Republic','Visual automation platform; AI integrations; EU-hosted options; GDPR workflow compliance'),
array('Manus','Automation & Agents','Manus AI','Singapore','Autonomous agent; high decision-influence'),
array('Microsoft Power Automate AI','Automation & Agents','Microsoft','US','Enterprise workflow automation; Copilot integration; M365 data access; DLP integration'),
array('n8n','Automation & Agents','n8n','Germany','Workflow automation; agentic actions'),
array('UiPath AI','Automation & Agents','UiPath','US','RPA + AI platform; document understanding; process mining; enterprise automation governance'),
array('Zapier AI','Automation & Agents','Zapier','US','Workflow automation with AI; 7000+ app integrations; data flow governance; cross-app exposure'),
array('Zapier Central','Automation & Agents','Zapier','US','Workflow automation; agentic actions'),
array('01.AI Yi','Chat & General LLMs','01.AI','China','Chinese open-source LLM; Kai-Fu Lee founded; cross-border data review advised'),
array('AI2 OLMo','Chat & General LLMs','Allen Institute for AI','US','Open-source language model; fully open training data; research transparency; nonprofit'),
array('Aleph Alpha','Chat & General LLMs','Aleph Alpha','Germany','European sovereign LLM; EU-hosted; GDPR-first; multilingual; Luminous model family'),
array('Apple Intelligence','Chat & General LLMs','Apple','US','On-device LLM; Private Cloud Compute; Apple silicon; minimal data exposure; privacy-first'),
array('Baichuan','Chat & General LLMs','Baichuan AI','China','Chinese open-source LLM; medical and legal fine-tunes; cross-border data review advised'),
array('Cerebras','Chat & General LLMs','Cerebras','US','Wafer-scale AI compute; inference API; on-prem options; high-performance computing'),
array('Character.ai','Chat & General LLMs','Character.AI','US','Persona chat; HR/appropriate-use risk'),
array('ChatGPT','Chat & General LLMs','OpenAI','US','General LLM assistant'),
array('Claude','Chat & General LLMs','Anthropic','US','General LLM assistant'),
array('Cohere Coral','Chat & General LLMs','Cohere','Canada','Enterprise chat AI; RAG-native; data privacy focus; Canadian vendor'),
array('Databricks DBRX','Chat & General LLMs','Databricks','US','Open-source general LLM; Mixture-of-Experts; enterprise training; already noted in Data & Analytics'),
array('DeepSeek','Chat & General LLMs','DeepSeek AI','China','Open-weight MoE; cross-border data review advised'),
array('Falcon (TII)','Chat & General LLMs','Technology Innovation Institute','UAE','UAE-hosted open-source LLM; sovereign AI; Apache 2.0; Middle East data residency'),
array('Fireworks AI','Chat & General LLMs','Fireworks AI','US','Fast inference API; open-source models; enterprise deployment; cost optimization'),
array('Gemini','Chat & General LLMs','Google','US','General LLM assistant'),
array('Grok','Chat & General LLMs','xAI','US','General LLM assistant'),
array('Huawei PanGu','Chat & General LLMs','Huawei','China','Chinese foundation model; cross-border data review advised; Ascend chip optimization'),
array('HyperWrite','Chat & General LLMs','HyperWrite','US','Writing assistant + agent'),
array('iFlytek Spark','Chat & General LLMs','iFlytek','China','Chinese voice+language AI; speech recognition; cross-border data review advised'),
array('InternLM (Shanghai AI Lab)','Chat & General LLMs','Shanghai AI Laboratory','China','Chinese open-source LLM; academic research; cross-border data review advised'),
array('JAIS (G42 / Inception)','Chat & General LLMs','G42 / Inception','UAE','Arabic-centric LLM; UAE sovereign AI; cultural alignment; Middle East data governance'),
array('Janitor AI','Chat & General LLMs','Janitor AI','US','Persona chat; HR/appropriate-use risk'),
array('Kimi','Chat & General LLMs','Moonshot AI','China','Long-context reasoning; cross-border data review advised'),
array('Llama (Meta)','Chat & General LLMs','Meta','US','Open-weight model family; often self-hosted'),
array('LMSYS Arena Models','Chat & General LLMs','LMSYS','US','Model evaluation platform; crowdsourced benchmarking; research transparency; no production use'),
array('Microsoft Copilot','Chat & General LLMs','Microsoft','US','Embedded across M365'),
array('Mistral / Le Chat','Chat & General LLMs','Mistral AI','France','EU-hosted option; GDPR relevant'),
array('Notion AI','Chat & General LLMs','Notion Labs','US','Embedded in workspace/knowledge base'),
array('NVIDIA Nemotron','Chat & General LLMs','NVIDIA','US','Enterprise LLM family; synthetic data generation; GPU-optimized; self-hosted options'),
array('Perplexity AI','Chat & General LLMs','Perplexity','US','Search-augmented LLM'),
array('Pi','Chat & General LLMs','Inflection AI','US','Conversational assistant'),
array('Poe','Chat & General LLMs','Quora','US','Multi-model aggregator'),
array('Replicate','Chat & General LLMs','Replicate','US','Model hosting and inference API; open-source models; community models; content policy'),
array('SambaNova','Chat & General LLMs','SambaNova Systems','US','Enterprise AI hardware+software; DataScale platform; on-prem deployment; sovereign AI'),
array('Samsung Gauss','Chat & General LLMs','Samsung','South Korea','On-device LLM; Galaxy AI; personal data processing; Korean vendor; local processing'),
array('SaulLM (Saul)','Chat & General LLMs','Saul','France','French legal-domain LLM; specialized training; EU data governance'),
array('SenseTime SenseChat','Chat & General LLMs','SenseTime','China','Chinese multimodal LLM; computer vision integration; cross-border data review advised'),
array('Slack AI','Chat & General LLMs','Salesforce','US','Embedded in messaging; message-corpus exposure'),
array('Snowflake Arctic','Chat & General LLMs','Snowflake','US','Enterprise-focused LLM; Apache 2.0 license; data cloud integration; commercial use'),
array('Together AI','Chat & General LLMs','Together AI','US','Decentralized cloud for open models; inference API; model hub; data residency options'),
array('You.com','Chat & General LLMs','You.com','US','Search-augmented LLM'),
array('Zoom AI Companion','Chat & General LLMs','Zoom','US','Meeting summarization; recording consent relevant'),
array('Doubao / Seed (ByteDance)','Chinese Foundation Models','ByteDance','China','Cross-border data review advised'),
array('ERNIE (Baidu)','Chinese Foundation Models','Baidu','China','Cross-border data review advised'),
array('GLM / Z.AI (Zhipu AI)','Chinese Foundation Models','Zhipu AI','China','Cross-border data review advised'),
array('Hunyuan (Tencent)','Chinese Foundation Models','Tencent','China','Cross-border data review advised'),
array('MiMo (Xiaomi)','Chinese Foundation Models','Xiaomi','China','Cross-border data review advised'),
array('MiniMax','Chinese Foundation Models','MiniMax','China','Cross-border data review advised'),
array('Qwen / Tongyi Qianwen (Alibaba)','Chinese Foundation Models','Alibaba Cloud','China','Cross-border data review advised'),
array('AI21 Labs API','Cloud AI Services & Model APIs','AI21 Labs','Israel','Jurassic models; enterprise API; data retention controls; compliance-focused'),
array('Amazon SageMaker','Cloud AI Services & Model APIs','Amazon Web Services','US','Full ML lifecycle management; model monitoring; bias detection; explainability tools'),
array('AWS Bedrock','Cloud AI Services & Model APIs','Amazon Web Services','US','Managed foundation model API service; IAM integration; VPC support; model evaluation tools; AgentCore for agent orchestration'),
array('Azure Machine Learning','Cloud AI Services & Model APIs','Microsoft','US','MLOps platform; AutoML; model registry; responsible AI toolkit integration'),
array('Azure OpenAI Service','Cloud AI Services & Model APIs','Microsoft','US','OpenAI models in Azure regions; enterprise content filtering; Entra ID integration; data residency controls'),
array('Cohere API','Cloud AI Services & Model APIs','Cohere','Canada','Enterprise-focused LLM API; strong on data privacy; RAG-optimized; multi-language support'),
array('Google Vertex AI','Cloud AI Services & Model APIs','Google Cloud','US','Unified ML platform; Model Garden; AutoML; MLOps lifecycle; BigQuery integration; TPU support'),
array('IBM watsonx','Cloud AI Services & Model APIs','IBM','US','Enterprise AI platform; watsonx.governance for agent inventory, behavior monitoring, hallucination detection; model-agnostic'),
array('NVIDIA NIM','Cloud AI Services & Model APIs','NVIDIA','US','Inference microservices for deploying foundation models; enterprise GPU optimization; self-hosted options'),
array('Anthropic Console','Coding & Developer Tools','Anthropic','US','API management console; prompt testing; evaluation tools; usage monitoring; cost controls'),
array('AutoGen (Microsoft)','Coding & Developer Tools','Microsoft','US','Multi-agent conversation framework; agent orchestration; code generation; Microsoft Research'),
array('Bolt.new','Coding & Developer Tools','StackBlitz','US','App generation'),
array('Chroma','Coding & Developer Tools','Chroma','US','Open-source embedding database; local-first; lightweight RAG; self-hosted option'),
array('Claude Code','Coding & Developer Tools','Anthropic','US','Agentic coding; source-code exposure'),
array('Comet ML','Coding & Developer Tools','Comet','US','ML experiment management; model monitoring; production tracking; team collaboration'),
array('CrewAI','Coding & Developer Tools','CrewAI','US','Multi-agent framework; agent collaboration; task delegation; emerging governance patterns'),
array('Cursor','Coding & Developer Tools','Anysphere','US','AI IDE; source-code exposure'),
array('Dify','Coding & Developer Tools','Dify','China','LLM app development platform; workflow orchestration; open-source; cross-border data review advised'),
array('DSPy','Coding & Developer Tools','Stanford NLP','US','Prompt optimization framework; Stanford research; systematic prompt engineering; reproducibility'),
array('Flowise','Coding & Developer Tools','Flowise','Open Source','Visual LLM workflow builder; low-code RAG; self-hosted; no-code agent building'),
array('GitHub Copilot','Coding & Developer Tools','Microsoft/GitHub','US','Code completion; source-code exposure'),
array('Google AI Studio','Coding & Developer Tools','Google','US','Model prototyping'),
array('Hugging Face','Coding & Developer Tools','Hugging Face','US','Model hub; supply-chain/AIBOM relevant'),
array('LangChain','Coding & Developer Tools','LangChain','US','LLM application framework; agent orchestration; supply-chain risk; rapid breaking changes'),
array('LlamaIndex','Coding & Developer Tools','LlamaIndex','US','RAG framework; data connectors; indexing strategies; enterprise RAG governance'),
array('Lovable','Coding & Developer Tools','Lovable','Sweden','App generation'),
array('Neptune.ai','Coding & Developer Tools','Neptune','Poland','ML metadata store; experiment tracking; model registry; EU-hosted options'),
array('OpenAI API / GPT models','Coding & Developer Tools','OpenAI','US','Direct API; usage-based cost escalation risk'),
array('OpenAI Playground / Dashboard','Coding & Developer Tools','OpenAI','US','API testing environment; fine-tuning; usage tracking; team management; cost escalation risk'),
array('Pinecone','Coding & Developer Tools','Pinecone','US','Vector database; RAG infrastructure; data residency options; enterprise security'),
array('Relevance AI','Coding & Developer Tools','Relevance AI','Australia','No-code AI workforce; agent teams; task automation; APAC data residency'),
array('Replit Agent','Coding & Developer Tools','Replit','US','Agentic coding; source-code exposure'),
array('Stack AI','Coding & Developer Tools','Stack AI','US','No-code AI app builder; enterprise deployment; workflow automation; data connector governance'),
array('Tabnine','Coding & Developer Tools','Tabnine','Israel','Code completion; self-host option'),
array('v0 (Vercel)','Coding & Developer Tools','Vercel','US','UI generation'),
array('Voiceflow','Coding & Developer Tools','Voiceflow','Canada','Conversational AI design; voice/chat agent builder; enterprise team features'),
array('Weaviate','Coding & Developer Tools','Weaviate','Netherlands','Open-source vector DB; GraphQL interface; EU-hosted; GDPR; hybrid search'),
array('Weights & Biases','Coding & Developer Tools','Weights & Biases','US','ML experiment tracking; model registry; artifact lineage; MLOps governance'),
array('Windsurf','Coding & Developer Tools','Cognition','US','AI IDE; source-code exposure'),
array('Alteryx AI','Data & Analytics AI','Alteryx','US','Analytics automation with AI; data blending; workflow governance; self-service analytics risk'),
array('Databricks AI / DBRX','Data & Analytics AI','Databricks','US','Lakehouse AI; DBRX open model; MLflow governance; Unity Catalog data governance; strong lineage tracking'),
array('Dataiku','Data & Analytics AI','Dataiku','France','Collaborative data science platform; MLOps; governance workflows; EU-hosted options; GDPR relevant'),
array('Palantir AIP','Data & Analytics AI','Palantir','US','Enterprise AI platform; Ontology-based governance; defense/intel focus; high-stakes decision influence'),
array('Snowflake Cortex','Data & Analytics AI','Snowflake','US','Native AI in data cloud; LLM functions; vector search; data residency controls; governance via Snowflake Horizon'),
array('Tableau AI (Einstein)','Data & Analytics AI','Salesforce','US','BI embedded AI; natural language queries; CRM data integration; Trust Layer governance'),
array('CheggMate','Education & Research AI','Chegg','US','Study AI assistant; academic help; student data; content accuracy; honor code implications'),
array('Grammarly for Education','Education & Research AI','Grammarly','US','Institutional writing support; student data; FERPA compliance; generative AI features'),
array('Khanmigo (Khan Academy)','Education & Research AI','Khan Academy','US','Educational AI tutor; student interaction data; COPPA compliance; pedagogical bias'),
array('Turnitin AI Detection','Education & Research AI','Turnitin','US','AI writing detection; academic integrity; false positive risk; student data privacy (FERPA)'),
array('Cohere Command R+','Emerging / Frontier AI','Cohere','Canada','Enterprise RAG-optimized model; tool use; autonomous retrieval; data grounding verification'),
array('Computer Use (Anthropic)','Emerging / Frontier AI','Anthropic','US','Computer control agent; desktop automation; system access; high-privilege operation risk'),
array('Devin (Cognition)','Emerging / Frontier AI','Cognition','US','Autonomous software engineer; full codebase access; high decision-influence; security critical'),
array('Figure AI','Emerging / Frontier AI','Figure AI','US','Humanoid robotics AI; physical world interaction; safety-critical; embodied AI governance'),
array('Mistral Large 2','Emerging / Frontier AI','Mistral AI','France','Advanced EU-hosted LLM; multilingual; GDPR-first design; sovereign AI option'),
array('Operator (OpenAI)','Emerging / Frontier AI','OpenAI','US','Autonomous web agent; browser control; credential exposure; action authorization risk'),
array('Physical Intelligence (pi0)','Emerging / Frontier AI','Physical Intelligence','US','General-purpose robot AI; physical task learning; safety-critical; emerging governance standards'),
array('Tesla Optimus','Emerging / Frontier AI','Tesla','US','Humanoid robot; factory automation; physical safety; worker interaction; liability'),
array('Aisera','Enterprise AI Platforms & Agent Orchestration','Aisera','US','AI service management platform; autonomous service desk; enterprise governance features'),
array('Cognigy','Enterprise AI Platforms & Agent Orchestration','Cognigy','Germany','Conversational AI platform for customer service; GDPR-compliant; EU-hosted options'),
array('Decagon','Enterprise AI Platforms & Agent Orchestration','Decagon','US','Customer support agent platform; omnichannel; model-agnostic; Watchtower monitoring'),
array('Glean','Enterprise AI Platforms & Agent Orchestration','Glean','US','Enterprise knowledge search AI; 100+ connectors; permission-aware retrieval; data access governance'),
array('Kore.ai','Enterprise AI Platforms & Agent Orchestration','Kore.ai','US','Enterprise agentic AI platform; multi-agent orchestration; comprehensive governance dashboard with audit logs, RBAC, and guardrails; 400+ Fortune 2000 customers'),
array('Moveworks','Enterprise AI Platforms & Agent Orchestration','Moveworks','US','Employee support automation; IT service desk agent; enterprise-grade access controls'),
array('Sierra','Enterprise AI Platforms & Agent Orchestration','Sierra','US','Conversational AI for customer experience; enterprise agent platform'),
array('Vellum','Enterprise AI Platforms & Agent Orchestration','Vellum','US','Personal AI assistant; on-device Mac app or cloud; cross-app memory; privacy-first design'),
array('Oracle Fusion AI','ERP & Business Application AI','Oracle','US','Embedded AI across ERP, HCM, SCM; autonomous database; enterprise data governance'),
array('SAP Joule','ERP & Business Application AI','SAP','Germany','ERP copilot across S/4HANA, SuccessFactors, Ariba; Joule Studio for custom agents; Knowledge Graph integration; ledger-modification risk'),
array('ServiceNow Now Assist','ERP & Business Application AI','ServiceNow','US','ITSM/HRSD embedded AI; workflow automation; enterprise process governance'),
array('Workday AI','ERP & Business Application AI','Workday','US','HR and finance AI; skills-based talent; predictive analytics; sensitive HR data exposure'),
array('AlphaSense','Finance & Legal AI','AlphaSense','US','Market intelligence AI; financial research; insider information risk; MNPI controls needed'),
array('Bloomberg GPT','Finance & Legal AI','Bloomberg','US','Finance-specific LLM; market data integration; proprietary data handling; trading decision risk'),
array('CoCounsel (Casetext)','Finance & Legal AI','Thomson Reuters','US','Legal research AI; litigation support; Westlaw integration; attorney work product risk'),
array('Harvey AI','Finance & Legal AI','Harvey','US','Legal AI assistant; contract drafting; case research; law firm data exposure; privilege concerns'),
array('Kira Systems','Finance & Legal AI','Litera','US','Contract analysis AI; legal document review; attorney-client privilege risk; confidential data'),
array('Vanta','Finance & Legal AI','Vanta','US','Security compliance automation; SOC 2, ISO 27001; continuous monitoring; audit automation'),
array('Epic AI (SlicerDicer, etc.)','Healthcare & Life Sciences AI','Epic Systems','US','Clinical decision support; patient data exposure; HIPAA critical; FDA SaMD considerations'),
array('Google Med-PaLM / MedLM','Healthcare & Life Sciences AI','Google','US','Medical LLM; clinical reasoning; healthcare data; HIPAA BAA required; diagnostic liability'),
array('Insilico Medicine','Healthcare & Life Sciences AI','Insilico Medicine','Hong Kong','Drug discovery AI; molecular design; IP generation; cross-border data (China/HK)'),
array('Merative (formerly Watson Health)','Healthcare & Life Sciences AI','Merative','US','Healthcare data analytics; clinical AI; population health; PHI governance'),
array('Tempus AI','Healthcare & Life Sciences AI','Tempus','US','Precision medicine AI; genomic data; clinical trial matching; genetic privacy (GINA)'),
array('Beamery','HR & Talent AI','Beamery','UK','Talent lifecycle management AI; skills ontology; DEI analytics; UK-hosted; GDPR relevant'),
array('Eightfold AI','HR & Talent AI','Eightfold','US','Talent intelligence platform; skills matching; DEI bias risk; high-stakes employment decisions'),
array('HireVue','HR & Talent AI','HireVue','US','Video interviewing AI; facial analysis controversy; algorithmic hiring bias; regulatory scrutiny'),
array('LinkedIn Recruiter AI','HR & Talent AI','Microsoft/LinkedIn','US','Talent acquisition AI; candidate matching; bias risk in hiring; GDPR for EU candidates'),
array('Paradox (Olivia)','HR & Talent AI','Paradox','US','Conversational recruiting AI; candidate screening; automated scheduling; hiring bias risk'),
array('Adobe Express AI','Image & Graphic Design','Adobe','US','Lightweight design AI; quick content creation; Adobe Firefly integration; commercial-safe'),
array('Adobe Firefly','Image & Graphic Design','Adobe','US','Image generation; commercial-safe training claim'),
array('Blender AI Add-ons','Image & Graphic Design','Blender Foundation','Netherlands','3D creation AI plugins; open-source; local processing; model provenance varies by plugin'),
array('Canva AI','Image & Graphic Design','Canva','Australia','Design generation'),
array('Clipdrop (Stability AI)','Image & Graphic Design','Stability AI','UK','Image editing AI suite; Stability AI ecosystem; open-weight tools; commercial licensing'),
array('DALL-E (OpenAI)','Image & Graphic Design','OpenAI','US','Image generation; IP provenance relevant'),
array('DeepAI','Image & Graphic Design','DeepAI','US','Image generation'),
array('Figma AI','Image & Graphic Design','Figma','US','Design AI; auto-layout; content generation; design system governance; Adobe acquisition context'),
array('Freepik AI','Image & Graphic Design','Freepik','Spain','Stock image AI generation; commercial licensing; EU-hosted; content moderation'),
array('Ideogram','Image & Graphic Design','Ideogram','Canada','Text-in-image generation; typography AI; commercial use; IP and copyright considerations'),
array('Jasper Art','Image & Graphic Design','Jasper','US','Marketing image generation; brand asset creation; commercial use; same vendor as Jasper copy'),
array('Krita AI','Image & Graphic Design','Krita Foundation','Netherlands','Open-source digital art; local AI plugins; no cloud dependency; community governance'),
array('Leonardo.ai','Image & Graphic Design','Canva','Australia','Image generation'),
array('Microsoft Designer','Image & Graphic Design','Microsoft','US','Image/design generation'),
array('Midjourney','Image & Graphic Design','Midjourney','US','Image generation; IP provenance relevant'),
array('Miro AI','Image & Graphic Design','Miro','US','Collaborative whiteboard AI; diagram generation; sticky note synthesis; creative IP risk'),
array('Photoroom','Image & Graphic Design','Photoroom','France','AI photo editing; background removal; e-commerce focus; EU data handling'),
array('Recraft','Image & Graphic Design','Recraft','UK','Vector image generation; brand consistency; commercial design; UK-hosted'),
array('Remove.bg','Image & Graphic Design','Canva','Australia','Image processing'),
array('Sketch AI','Image & Graphic Design','Sketch','Netherlands','Design tool AI; macOS native; local processing option; EU design data'),
array('Stable Diffusion','Image & Graphic Design','Stability AI','UK','Open-weight image model'),
array('Asana AI','Notes, Knowledge & Meetings','Asana','US','Work management AI; goal tracking; team productivity analytics; data residency options'),
array('Avoma','Notes, Knowledge & Meetings','Avoma','US','Meeting intelligence AI; conversation analytics; coaching; revenue team data'),
array('Box AI','Notes, Knowledge & Meetings','Box','US','Enterprise content AI; metadata; governance; compliance; retention policies'),
array('Cisco Webex AI','Notes, Knowledge & Meetings','Cisco','US','Meeting intelligence; real-time translation; noise removal; enterprise security'),
array('ClickUp AI','Notes, Knowledge & Meetings','ClickUp','US','All-in-one productivity AI; document generation; task automation; broad data access'),
array('Coda AI','Notes, Knowledge & Meetings','Coda','US','All-in-one doc AI; automation; team data; enterprise governance features'),
array('Confluence AI','Notes, Knowledge & Meetings','Atlassian','Australia','Team wiki AI; smart links; automation; Atlassian Cloud governance'),
array('Dropbox AI','Notes, Knowledge & Meetings','Dropbox','US','Cloud storage AI; document summaries; team data; sharing controls'),
array('Fathom','Notes, Knowledge & Meetings','Fathom','US','Meeting notetaker AI; auto-summaries; CRM sync; consent and privacy'),
array('Fireflies.ai','Notes, Knowledge & Meetings','Fireflies.ai','US','Meeting transcription; consent relevant'),
array('Gong','Notes, Knowledge & Meetings','Gong','US','Revenue intelligence AI; call analysis; deal coaching; sensitive sales data exposure'),
array('Google Drive AI','Notes, Knowledge & Meetings','Google','US','Cloud storage AI; Gemini integration; Workspace data; sharing governance'),
array('Google Meet AI','Notes, Knowledge & Meetings','Google','US','Meeting summaries; live captions; note-taking; Google Workspace data'),
array('Grain','Notes, Knowledge & Meetings','Grain','US','Meeting recording AI; highlight clips; CRM integration; consent and sharing'),
array('Logseq AI','Notes, Knowledge & Meetings','Logseq','Open Source','Open-source knowledge base; local-first; graph database; privacy-focused'),
array('Mem','Notes, Knowledge & Meetings','Mem Labs','US','Personal knowledge base'),
array('Microsoft Teams AI','Notes, Knowledge & Meetings','Microsoft','US','Meeting recaps; intelligent recap; Copilot integration; M365 data exposure'),
array('Monday.com AI','Notes, Knowledge & Meetings','monday.com','Israel','Work OS AI; project automation; cross-functional data; Israeli data transfer considerations'),
array('NotebookLM','Notes, Knowledge & Meetings','Google','US','Document grounding; ingests uploaded corpora'),
array('Notion Q&A','Notes, Knowledge & Meetings','Notion Labs','US','Knowledge base AI Q&A; workspace corpus access; permission-aware but broad exposure risk'),
array('Obsidian AI','Notes, Knowledge & Meetings','Obsidian','Canada','Local-first knowledge AI; plugins; privacy-focused; no cloud dependency'),
array('Otter.ai','Notes, Knowledge & Meetings','Otter.ai','US','Meeting transcription; consent relevant'),
array('Read.ai','Notes, Knowledge & Meetings','Read','US','Meeting analytics AI; engagement scoring; wellness insights; behavioral data privacy'),
array('SharePoint AI','Notes, Knowledge & Meetings','Microsoft','US','Enterprise content AI; Copilot integration; M365 governance; DLP'),
array('Supernormal','Notes, Knowledge & Meetings','Supernormal','US','Meeting notes AI; action items; CRM sync; team productivity data'),
array('tl;dv','Notes, Knowledge & Meetings','tl;dv','Germany','Meeting recorder AI; timestamped notes; EU-hosted; GDPR; consent management'),
array('Trello AI (Atlassian)','Notes, Knowledge & Meetings','Atlassian','Australia','Project management AI; workflow automation; team data exposure; Atlassian Cloud governance'),
array('Hugging Face Transformers','Open Source & Self-Hosted Models','Hugging Face','US','Model hub and inference library; supply-chain/AIBOM critical; model card verification; security scanning'),
array('llama.cpp','Open Source & Self-Hosted Models','Georgi Gerganov','Open Source','Lightweight LLM inference; C++ implementation; edge deployment; model provenance tracking'),
array('Ollama','Open Source & Self-Hosted Models','Ollama','US','Local LLM runner; self-hosted; no data exfiltration; model supply-chain verification needed'),
array('PyTorch','Open Source & Self-Hosted Models','Meta / Linux Foundation','US','Deep learning framework; model checkpoint governance; TorchServe deployment; research-to-production lineage'),
array('TensorFlow / Keras','Open Source & Self-Hosted Models','Google','US','ML framework; model serialization risks; custom model governance; TensorFlow Extended (TFX) for MLOps'),
array('vLLM','Open Source & Self-Hosted Models','UC Berkeley / vLLM Team','US','High-throughput inference engine; open-source; self-hosted; no external data sharing'),
array('Connected Papers','Search, Research, Translation & Other','Connected Papers','Israel','Visual paper graph; literature discovery; academic research; Israeli vendor'),
array('Consensus','Search, Research, Translation & Other','Consensus','US','Research search'),
array('DeepL','Search, Research, Translation & Other','DeepL','Germany','Translation; EU-hosted'),
array('Elicit','Search, Research, Translation & Other','Elicit','US','Research assistant AI; paper analysis; systematic review; academic integrity'),
array('Groq','Search, Research, Translation & Other','Groq','US','Inference acceleration'),
array('Lokalise AI','Search, Research, Translation & Other','Lokalise','UK','Localization AI; continuous translation; developer workflow; UK-hosted'),
array('Perplexity Enterprise Pro','Search, Research, Translation & Other','Perplexity','US','Enterprise search AI; internal knowledge search; data indexing; SSO; audit logs'),
array('Phrase (Memsource)','Search, Research, Translation & Other','Phrase','Czech Republic','Enterprise localization AI; TMS; machine translation; EU-hosted; GDPR'),
array('ResearchRabbit','Search, Research, Translation & Other','ResearchRabbit','US','Research discovery AI; paper recommendations; collaboration features; academic data'),
array('Salesforce Einstein / Agentforce','Search, Research, Translation & Other','Salesforce','US','CRM-embedded AI + agents'),
array('Scite','Search, Research, Translation & Other','Scite','US','Smart citation analysis; claim verification; research quality; academic trust'),
array('Semantic Scholar','Search, Research, Translation & Other','Allen Institute for AI','US','Academic search AI; paper summaries; citation graphs; nonprofit research focus'),
array('Smartcat','Search, Research, Translation & Other','Smartcat','US','Translation management AI; CAT tool; vendor marketplace; translation memory governance'),
array('Unbabel','Search, Research, Translation & Other','Unbabel','Portugal','AI-human translation; quality estimation; enterprise localization; EU vendor'),
array('Wayground','Search, Research, Translation & Other','Wayground','US','Education tooling'),
array('You.com Enterprise','Search, Research, Translation & Other','You.com','US','Private search AI; no tracking; enterprise deployment; data privacy focus'),
array('CrowdStrike Charlotte AI','Security & Identity AI','CrowdStrike','US','Security operations AI; threat detection; autonomous response; high-privilege access'),
array('Darktrace','Security & Identity AI','Darktrace','UK','Self-learning AI security; anomaly detection; autonomous response; UK-hosted; GDPR relevant'),
array('Okta AI','Security & Identity AI','Okta','US','Identity AI; risk-based authentication; privileged access; identity threat detection'),
array('Palo Alto Networks Precision AI','Security & Identity AI','Palo Alto Networks','US','Network security AI; Zero Trust integration; autonomous threat response; critical infrastructure'),
array('SentinelOne Purple AI','Security & Identity AI','SentinelOne','US','Endpoint security AI; autonomous response; XDR platform; kill-switch capabilities'),
array('Zscaler AI','Security & Identity AI','Zscaler','US','Cloud security AI; SSE platform; data loss prevention; AI traffic inspection'),
array('Beautiful.ai','Slides & Presentations','Beautiful.ai','US','Presentation generation'),
array('Decktopus','Slides & Presentations','Decktopus','US','AI presentation maker; automated design; content generation; data exposure'),
array('Gamma','Slides & Presentations','Gamma','US','Presentation generation'),
array('Pitch AI','Slides & Presentations','Pitch','Germany','Presentation software AI; collaboration; template generation; EU-hosted'),
array('Presentations.AI','Slides & Presentations','Presentations.AI','US','Text-to-presentation AI; automated layouts; brand templates; content governance'),
array('SlidesAI','Slides & Presentations','SlidesAI','India','Presentation generation'),
array('Tome','Slides & Presentations','Tome','US','AI storytelling; presentation generation; narrative design; creative IP'),
array('2short.ai','Video Generation & Editing','2short','US','YouTube shorts AI; clip extraction; content automation; platform dependency'),
array('CapCut','Video Generation & Editing','ByteDance','China','Video editing; cross-border data review advised'),
array('Captions AI','Video Generation & Editing','Captions','US','AI video editing; eye contact correction; dubbing; likeness manipulation consent'),
array('Colossyan','Video Generation & Editing','Colossyan','UK','AI video avatars; enterprise training; consent management; UK-hosted'),
array('D-ID','Video Generation & Editing','D-ID','Israel','Talking head AI; photo animation; likeness rights; deepfake risk; Israeli vendor'),
array('DaVinci Resolve AI','Video Generation & Editing','Blackmagic Design','Australia','Professional video AI; color grading; facial recognition; local processing option'),
array('Descript','Video Generation & Editing','Descript','US','Audio/video editing + voice cloning'),
array('Elai.io','Video Generation & Editing','Elai','US','AI avatar video; text-to-video; multilingual; enterprise training; consent'),
array('Filmora AI','Video Generation & Editing','Wondershare','China','Video editing'),
array('Final Cut Pro AI','Video Generation & Editing','Apple','US','Mac video editing AI; on-device processing; privacy-first; Apple silicon optimization'),
array('Fliki','Video Generation & Editing','Fliki','US','Video + voice generation'),
array('Hailuo AI (MiniMax)','Video Generation & Editing','MiniMax','China','Video generation; cross-border data review advised; same vendor as MiniMax LLM'),
array('Headliner','Video Generation & Editing','Headliner','US','Podcast/video promotion; audiogram generation; social media; content marketing'),
array('HeyGen','Video Generation & Editing','HeyGen','US','AI avatars; likeness/consent risk'),
array('Hour One','Video Generation & Editing','Hour One','Israel','AI avatar video; virtual presenters; enterprise video; likeness consent; Israeli vendor'),
array('iMovie AI','Video Generation & Editing','Apple','US','Consumer video editing; trailer templates; on-device; Apple privacy'),
array('InShot AI','Video Generation & Editing','InShot','China','Mobile video editing AI; social content; cross-border data review advised'),
array('InVideo','Video Generation & Editing','InVideo','India','Video generation'),
array('Kling AI (Kuaishou)','Video Generation & Editing','Kuaishou','China','Video generation model; cross-border data review advised; content moderation; Chinese vendor'),
array('Krea AI','Video Generation & Editing','Krea','US','Real-time video generation; creative tool; content moderation; emerging platform'),
array('Loom AI','Video Generation & Editing','Loom','US','Async video AI; auto-chapters; summaries; transcription; Atlassian acquisition context'),
array('Luma AI','Video Generation & Editing','Luma AI','US','3D/video generation'),
array('Lumen5','Video Generation & Editing','Lumen5','Canada','Video generation'),
array('Microsoft Clipchamp AI','Video Generation & Editing','Microsoft','US','Video editing AI; M365 integration; auto-caption; text-to-speech; enterprise data'),
array('Munch','Video Generation & Editing','Munch','Israel','Content repurposing AI; auto-editing; social clips; trend analysis; Israeli vendor'),
array('OpusClip','Video Generation & Editing','OpusClip','US','Video repurposing'),
array('Pictory','Video Generation & Editing','Pictory','US','Video generation'),
array('Pika Labs','Video Generation & Editing','Pika Labs','US','Video generation; meme/creative focus; content policy; IP provenance'),
array('Premiere Pro AI (Adobe)','Video Generation & Editing','Adobe','US','Professional video AI; generative extend; color match; commercial-safe training'),
array('Repurpose.io','Video Generation & Editing','Repurpose','US','Content distribution automation; multi-platform; workflow automation; API access'),
array('Runway','Video Generation & Editing','Runway','US','Video generation'),
array('Sora (OpenAI)','Video Generation & Editing','OpenAI','US','Video generation; provenance/disclosure relevant'),
array('Splice','Video Generation & Editing','Splice','US','Mobile video editing; music licensing; content creation; GoPro ownership'),
array('Submagic','Video Generation & Editing','Submagic','France','Auto-caption AI; video subtitles; emoji/sticker automation; EU vendor'),
array('Synthesia','Video Generation & Editing','Synthesia','UK','AI avatars; likeness/consent risk'),
array('Veed.io AI','Video Generation & Editing','Veed','UK','Online video editing AI; auto-subtitle; text-to-speech; UK-hosted'),
array('Videoleap','Video Generation & Editing','Lightricks','Israel','Mobile video editing AI; effects; templates; Israeli vendor'),
array('Vidu (Tsinghua / Shengshu)','Video Generation & Editing','Shengshu Technology','China','Video generation model; academic spin-off; cross-border data review advised'),
array('Vizard AI','Video Generation & Editing','Vizard','US','Video repurposing; auto-clipping; social media; content strategy AI'),
array('Wavve','Video Generation & Editing','Wavve','US','Audio-to-video AI; podcast clips; waveform videos; social media content'),
array('Wistia','Video Generation & Editing','Wistia','US','Video hosting AI; analytics; marketing video; data privacy; engagement tracking'),
array('Wondershare Virbo','Video Generation & Editing','Wondershare','China','AI avatar video; cross-border data review advised; likeness consent; Chinese vendor'),
array('Zeemo','Video Generation & Editing','Zeemo','US','Video captioning AI; translation; subtitle styling; content accessibility'),
array('Adobe Podcast AI','Voice & Audio','Adobe','US','Audio enhancement AI; speech enhancement; microphone check; commercial-safe training claim'),
array('AIVA','Voice & Audio','AIVA Technologies','Luxembourg','Classical music AI composer; copyright assignment; EU-hosted; commercial licensing'),
array('Altered','Voice & Audio','Altered','UK','Professional voice editing; voice morphing; dubbing; consent management; UK-hosted'),
array('AssemblyAI','Voice & Audio','AssemblyAI','US','Speech AI API; transcription; summarization; PII redaction; enterprise security'),
array('Deepgram','Voice & Audio','Deepgram','US','Speech recognition API; real-time transcription; model customization; on-prem option'),
array('Descript Overdub','Voice & Audio','Descript','US','Voice cloning for editing; consent recording required; deepfake risk; media integrity'),
array('ElevenLabs','Voice & Audio','ElevenLabs','US','Voice cloning; likeness/consent risk'),
array('Krisp','Voice & Audio','Krisp','US','Audio processing'),
array('Lovo (Genny)','Voice & Audio','Lovo','US','Voice cloning and synthesis; likeness consent; commercial voiceover; synthetic media disclosure'),
array('Murf.ai','Voice & Audio','Murf','India','Voice synthesis'),
array('Play.ht','Voice & Audio','PlayAI','US','Voice synthesis'),
array('Resemble AI','Voice & Audio','Resemble AI','US','Voice cloning; likeness/consent risk'),
array('Respeecher','Voice & Audio','Respeecher','Ukraine','Voice cloning for media; entertainment focus; likeness rights; Ukrainian vendor'),
array('Rev AI','Voice & Audio','Rev','US','Speech-to-text API; transcription; captioning; human + AI hybrid; data confidentiality'),
array('Soundraw','Voice & Audio','Soundraw','Japan','Royalty-free AI music; commercial license; JASRAC considerations for Japan use'),
array('Speechmatics','Voice & Audio','Speechmatics','UK','Speech-to-text; real-time translation; accent-agnostic; UK-hosted; GDPR'),
array('Suno','Voice & Audio','Suno','US','Music generation; IP provenance relevant'),
array('Udio','Voice & Audio','Udio','US','AI music generation; copyright risk; likeness in vocals; RIAA litigation context'),
array('Voicemod','Voice & Audio','Voicemod','Spain','Real-time voice changing; gaming/streaming; content moderation; EU vendor'),
array('Whisper API (OpenAI)','Voice & Audio','OpenAI','US','Speech recognition; transcription; translation; API data retention policy'),
array('Anyword','Writing & Editing','Anyword','US','Predictive performance AI copy; marketing optimization; data-driven; performance claims'),
array('Clearscope','Writing & Editing','Clearscope','US','Content optimization AI; readability scoring; competitor content analysis'),
array('Copy.ai','Writing & Editing','Copy.ai','US','Marketing copy / GTM workflows'),
array('Frase','Writing & Editing','Frase','US','SEO content AI; SERP analysis; competitive data scraping; search algorithm dependency'),
array('Grammarly','Writing & Editing','Grammarly','US','Reads document text broadly'),
array('Jasper','Writing & Editing','Jasper','US','Marketing copy'),
array('Jasper Campaigns','Writing & Editing','Jasper','US','End-to-end marketing campaigns AI; brand voice; cross-channel content; governance dashboard'),
array('MarketMuse','Writing & Editing','MarketMuse','US','Content strategy AI; topic modeling; site-wide content audit; competitive intelligence'),
array('QuillBot','Writing & Editing','Course Hero','US','Paraphrasing'),
array('Rytr','Writing & Editing','Rytr','US','Marketing copy'),
array('Surfer SEO','Writing & Editing','Surfer','Poland','SEO optimization AI; content scoring; NLP analysis; EU-hosted options'),
array('Typeface','Writing & Editing','Typeface','US','Enterprise content AI; brand-customized models; marketing asset generation; high decision-influence'),
array('Wordtune','Writing & Editing','AI21 Labs','Israel','Rewriting'),
array('Writer.com','Writing & Editing','Writer','US','Enterprise writing AI; brand governance; style guide enforcement; hallucination detection; PALMYRA models'),
array('WriteSonic','Writing & Editing','Writesonic','US','Marketing copy'),
);
