name: Deploy WordPress to GoDaddy via rsync
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Synchronize Files with GoDaddy WordPress Hosting Server
        uses: godaddy-wordpress/gd-wordpress-deployer@v1
        with:
          remote_host: "0g6.84f.myftpupload.com"
          ssh_user: "git_deployer_0ce5dfd9f0_1166798"
          ssh_private_key: ${{secrets.PRIVATE_KEY}}
          deployment_dest: ""
